In [ ]:
from sentence_transformers import SentenceTransformer, util

# Charger le modèle
model = SentenceTransformer("sentence-transformers/LaBSE")

# Question et réponses
question = "I bɛ se ka fo bonjour ci ?"  # Comment dit-on bonjour ?
bonne_reponse = "On dit 'I ni sogoma'."
mauvaise_reponse = "Le chat mange une banane."

# Encoder les phrases
emb_q = model.encode(question, convert_to_tensor=True)
emb_bonne = model.encode(bonne_reponse, convert_to_tensor=True)
emb_mauvaise = model.encode(mauvaise_reponse, convert_to_tensor=True)

# Calculer la similarité cosinus
score_bonne = util.cos_sim(emb_q, emb_bonne).item()
score_mauvaise = util.cos_sim(emb_q, emb_mauvaise).item()

print(f"Score bonne réponse : {score_bonne:.4f}")
print(f"Score mauvaise réponse : {score_mauvaise:.4f}")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.88G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

Score bonne réponse : 0.0864
Score mauvaise réponse : 0.1550

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Phrase de test
question = "I ye ni sisan kalan ka don."
true_answer = "Wo ka di! A t'a kɛ kalan kɔnɔ."
false_answer = "N bɛ taa so."

# Liste des modèles à tester
models = {
    "LaBSE": "sentence-transformers/LaBSE",
    "MiniLM-multilingual": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    # Ajoute d'autres modèles ici si disponibles sur HuggingFace
}

# Fonction pour calculer la similarité
def get_similarity(model_name, model, question, answer):
    embeddings = model.encode([question, answer])
    sim_score = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return sim_score

# Tester chaque modèle
for name, model_id in models.items():
    print(f"\n🧪 Modèle : {name}")
    model = SentenceTransformer(model_id)

    sim_true = get_similarity(name, model, question, true_answer)
    sim_false = get_similarity(name, model, question, false_answer)

    print(f"✔️ Similarité avec la BONNE réponse : {sim_true:.4f}")
    print(f"❌ Similarité avec la FAUSSE réponse : {sim_false:.4f}")

🧪 Modèle : LaBSE
✔️ Similarité avec la BONNE réponse : 0.1936
❌ Similarité avec la FAUSSE réponse : 0.2411

🧪 Modèle : MiniLM-multilingual

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✔️ Similarité avec la BONNE réponse : 0.3674
❌ Similarité avec la FAUSSE réponse : 0.4519

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Phrase de test
question = "I ye ni sisan kalan ka don."  # Je veux apprendre maintenant
true_answer = "Wo ka di! A t'a kɛ kalan kɔnɔ."  # Bonne réponse
false_answer = "N bɛ taa so."  # Fausse réponse

# Liste des modèles à tester (plus large)
models = {
    "MiniLM-multilingual": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    "LaBSE": "sentence-transformers/LaBSE",
    "E5-small": "intfloat/multilingual-e5-small",
    "E5-base": "intfloat/multilingual-e5-base",
    "GTE-large": "thenlper/gte-large",
    "Jina-v2": "jinaai/jina-embeddings-v2-base-en"
    # Tu peux ajouter ici "bge-m3" si tu veux le tester plus tard
}

def get_similarity(model, question, answer):
    embeddings = model.encode([question, answer])
    score = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return score

# Tester les modèles
for name, model_id in models.items():
    print(f"\n🧪 Modèle : {name}")
    model = SentenceTransformer(model_id)

    sim_true = get_similarity(model, question, true_answer)
    sim_false = get_similarity(model, question, false_answer)

    print(f"✔️ Similarité avec la BONNE réponse : {sim_true:.4f}")
    print(f"❌ Similarité avec la FAUSSE réponse : {sim_false:.4f}")

🧪 Modèle : MiniLM-multilingual
✔️ Similarité avec la BONNE réponse : 0.3674
❌ Similarité avec la FAUSSE réponse : 0.4519

🧪 Modèle : LaBSE
✔️ Similarité avec la BONNE réponse : 0.1936
❌ Similarité avec la FAUSSE réponse : 0.2411

🧪 Modèle : E5-small

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

✔️ Similarité avec la BONNE réponse : 0.8960
❌ Similarité avec la FAUSSE réponse : 0.8706

🧪 Modèle : E5-base

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

✔️ Similarité avec la BONNE réponse : 0.8606
❌ Similarité avec la FAUSSE réponse : 0.8348

🧪 Modèle : GTE-large

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/619 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/670M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/342 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

✔️ Similarité avec la BONNE réponse : 0.8486
❌ Similarité avec la FAUSSE réponse : 0.8137

🧪 Modèle : Jina-v2

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/275M [00:00<?, ?B/s]

Some weights of BertModel were not initialized from the model checkpoint at jinaai/jina-embeddings-v2-base-en and are newly initialized: ['embeddings.position_embeddings.weight', 'encoder.layer.0.intermediate.dense.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.0.output.LayerNorm.bias', 'encoder.layer.0.output.LayerNorm.weight', 'encoder.layer.0.output.dense.bias', 'encoder.layer.0.output.dense.weight', 'encoder.layer.1.intermediate.dense.bias', 'encoder.layer.1.intermediate.dense.weight', 'encoder.layer.1.output.LayerNorm.bias', 'encoder.layer.1.output.LayerNorm.weight', 'encoder.layer.1.output.dense.bias', 'encoder.layer.1.output.dense.weight', 'encoder.layer.10.intermediate.dense.bias', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.10.output.LayerNorm.bias', 'encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.10.output.dense.bias', 'encoder.layer.10.output.dense.weight', 'encoder.layer.11.intermediate.dense.bias', 'encoder.layer.11.intermediate.dense.weight', 'encoder.layer.11.output.LayerNorm.bias', 'encoder.layer.11.output.LayerNorm.weight', 'encoder.layer.11.output.dense.bias', 'encoder.layer.11.output.dense.weight', 'encoder.layer.2.intermediate.dense.bias', 'encoder.layer.2.intermediate.dense.weight', 'encoder.layer.2.output.LayerNorm.bias', 'encoder.layer.2.output.LayerNorm.weight', 'encoder.layer.2.output.dense.bias', 'encoder.layer.2.output.dense.weight', 'encoder.layer.3.intermediate.dense.bias', 'encoder.layer.3.intermediate.dense.weight', 'encoder.layer.3.output.LayerNorm.bias', 'encoder.layer.3.output.LayerNorm.weight', 'encoder.layer.3.output.dense.bias', 'encoder.layer.3.output.dense.weight', 'encoder.layer.4.intermediate.dense.bias', 'encoder.layer.4.intermediate.dense.weight', 'encoder.layer.4.output.LayerNorm.bias', 'encoder.layer.4.output.LayerNorm.weight', 'encoder.layer.4.output.dense.bias', 'encoder.layer.4.output.dense.weight', 'encoder.layer.5.intermediate.dense.bias', 'encoder.layer.5.intermediate.dense.weight', 'encoder.layer.5.output.LayerNorm.bias', 'encoder.layer.5.output.LayerNorm.weight', 'encoder.layer.5.output.dense.bias', 'encoder.layer.5.output.dense.weight', 'encoder.layer.6.intermediate.dense.bias', 'encoder.layer.6.intermediate.dense.weight', 'encoder.layer.6.output.LayerNorm.bias', 'encoder.layer.6.output.LayerNorm.weight', 'encoder.layer.6.output.dense.bias', 'encoder.layer.6.output.dense.weight', 'encoder.layer.7.intermediate.dense.bias', 'encoder.layer.7.intermediate.dense.weight', 'encoder.layer.7.output.LayerNorm.bias', 'encoder.layer.7.output.LayerNorm.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.7.output.dense.weight', 'encoder.layer.8.intermediate.dense.bias', 'encoder.layer.8.intermediate.dense.weight', 'encoder.layer.8.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.8.output.dense.bias', 'encoder.layer.8.output.dense.weight', 'encoder.layer.9.intermediate.dense.bias', 'encoder.layer.9.intermediate.dense.weight', 'encoder.layer.9.output.LayerNorm.bias', 'encoder.layer.9.output.LayerNorm.weight', 'encoder.layer.9.output.dense.bias', 'encoder.layer.9.output.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/373 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.

✔️ Similarité avec la BONNE réponse : 0.3427
❌ Similarité avec la FAUSSE réponse : 0.2698

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from deep_translator import GoogleTranslator
import numpy as np

# Traduction en français (via Google Translate)
def translate_to_french(text):
    return GoogleTranslator(source='auto', target='fr').translate(text)

# Liste des modèles à tester
models = {
    "E5-small": "intfloat/multilingual-e5-small",
    "E5-base": "intfloat/multilingual-e5-base",
    "GTE-large": "thenlper/gte-large",
    "Jina-v2": "jinaai/jina-embeddings-v2-base-en"
}

# Exemples en Bambara
question_bambara = "I ye ni sisan kalan ka don."
true_answer_bambara = "Wo ka di! A t'a kɛ kalan kɔnɔ."
false_answer_bambara = "N bɛ taa so."

# Traduire tout en français
question_fr = translate_to_french(question_bambara)
true_answer_fr = translate_to_french(true_answer_bambara)
false_answer_fr = translate_to_french(false_answer_bambara)

print("\n🔁 Traductions françaises :")
print(f"Question : {question_fr}")
print(f"Bonne réponse : {true_answer_fr}")
print(f"Mauvaise réponse : {false_answer_fr}")

# Fonction de similarité
def get_similarity(model, q, a):
    embeddings = model.encode([q, a])
    score = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return score

# Tester tous les modèles sur les textes traduits
for name, model_id in models.items():
    print(f"\n🧪 Modèle : {name}")
    model = SentenceTransformer(model_id)

    sim_true = get_similarity(model, question_fr, true_answer_fr)
    sim_false = get_similarity(model, question_fr, false_answer_fr)

    print(f"✔️ Similarité avec la BONNE réponse : {sim_true:.4f}")
    print(f"❌ Similarité avec la FAUSSE réponse : {sim_false:.4f}")

🔁 Traductions françaises :
Question : Vous avez maintenant entre.
Bonne réponse : Le mangerait! Vous vous verrouillez comme Kala.
Mauvaise réponse : Je rentre à la maison.

🧪 Modèle : E5-small
✔️ Similarité avec la BONNE réponse : 0.8564
❌ Similarité avec la FAUSSE réponse : 0.8636

🧪 Modèle : E5-base
✔️ Similarité avec la BONNE réponse : 0.8326
❌ Similarité avec la FAUSSE réponse : 0.8270

🧪 Modèle : GTE-large
✔️ Similarité avec la BONNE réponse : 0.8456
❌ Similarité avec la FAUSSE réponse : 0.8559

🧪 Modèle : Jina-v2

Some weights of BertModel were not initialized from the model checkpoint at jinaai/jina-embeddings-v2-base-en and are newly initialized: ['embeddings.position_embeddings.weight', 'encoder.layer.0.intermediate.dense.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.0.output.LayerNorm.bias', 'encoder.layer.0.output.LayerNorm.weight', 'encoder.layer.0.output.dense.bias', 'encoder.layer.0.output.dense.weight', 'encoder.layer.1.intermediate.dense.bias', 'encoder.layer.1.intermediate.dense.weight', 'encoder.layer.1.output.LayerNorm.bias', 'encoder.layer.1.output.LayerNorm.weight', 'encoder.layer.1.output.dense.bias', 'encoder.layer.1.output.dense.weight', 'encoder.layer.10.intermediate.dense.bias', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.10.output.LayerNorm.bias', 'encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.10.output.dense.bias', 'encoder.layer.10.output.dense.weight', 'encoder.layer.11.intermediate.dense.bias', 'encoder.layer.11.intermediate.dense.weight', 'encoder.layer.11.output.LayerNorm.bias', 'encoder.layer.11.output.LayerNorm.weight', 'encoder.layer.11.output.dense.bias', 'encoder.layer.11.output.dense.weight', 'encoder.layer.2.intermediate.dense.bias', 'encoder.layer.2.intermediate.dense.weight', 'encoder.layer.2.output.LayerNorm.bias', 'encoder.layer.2.output.LayerNorm.weight', 'encoder.layer.2.output.dense.bias', 'encoder.layer.2.output.dense.weight', 'encoder.layer.3.intermediate.dense.bias', 'encoder.layer.3.intermediate.dense.weight', 'encoder.layer.3.output.LayerNorm.bias', 'encoder.layer.3.output.LayerNorm.weight', 'encoder.layer.3.output.dense.bias', 'encoder.layer.3.output.dense.weight', 'encoder.layer.4.intermediate.dense.bias', 'encoder.layer.4.intermediate.dense.weight', 'encoder.layer.4.output.LayerNorm.bias', 'encoder.layer.4.output.LayerNorm.weight', 'encoder.layer.4.output.dense.bias', 'encoder.layer.4.output.dense.weight', 'encoder.layer.5.intermediate.dense.bias', 'encoder.layer.5.intermediate.dense.weight', 'encoder.layer.5.output.LayerNorm.bias', 'encoder.layer.5.output.LayerNorm.weight', 'encoder.layer.5.output.dense.bias', 'encoder.layer.5.output.dense.weight', 'encoder.layer.6.intermediate.dense.bias', 'encoder.layer.6.intermediate.dense.weight', 'encoder.layer.6.output.LayerNorm.bias', 'encoder.layer.6.output.LayerNorm.weight', 'encoder.layer.6.output.dense.bias', 'encoder.layer.6.output.dense.weight', 'encoder.layer.7.intermediate.dense.bias', 'encoder.layer.7.intermediate.dense.weight', 'encoder.layer.7.output.LayerNorm.bias', 'encoder.layer.7.output.LayerNorm.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.7.output.dense.weight', 'encoder.layer.8.intermediate.dense.bias', 'encoder.layer.8.intermediate.dense.weight', 'encoder.layer.8.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.8.output.dense.bias', 'encoder.layer.8.output.dense.weight', 'encoder.layer.9.intermediate.dense.bias', 'encoder.layer.9.intermediate.dense.weight', 'encoder.layer.9.output.LayerNorm.bias', 'encoder.layer.9.output.LayerNorm.weight', 'encoder.layer.9.output.dense.bias', 'encoder.layer.9.output.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✔️ Similarité avec la BONNE réponse : 0.4460
❌ Similarité avec la FAUSSE réponse : 0.3957

In [ ]:
from sentence_transformers import SentenceTransformer
from transformers import AutoModel, AutoTokenizer
import torch
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Phrases de test
question = "I ye ni sisan kalan ka don."  # "Je veux apprendre maintenant"
true_answer = "Wo ka di! A t'a kɛ kalan kɔnɔ."  # "Bonne réponse"
false_answer = "N bɛ taa so."  # "Fausse réponse"

# === 1. Test avec BGE-M3 ===
def test_bge_m3():
    print("\n🔍 Testing BGE-M3...")
    model = SentenceTransformer("BAAI/bge-m3", device="cpu")  # Ajoutez device="cuda" si vous avez un GPU

    # Encodage
    question_embed = model.encode(question)
    true_embed = model.encode(true_answer)
    false_embed = model.encode(false_answer)

    # Similarité cosinus
    sim_true = cosine_similarity([question_embed], [true_embed])[0][0]
    sim_false = cosine_similarity([question_embed], [false_embed])[0][0]

    print(f"✔️ Similarité avec la BONNE réponse : {sim_true:.4f}")
    print(f"❌ Similarité avec la FAUSSE réponse : {sim_false:.4f}")

# === 2. Test avec AfroXLM-R (comme il n'est pas dans SentenceTransformers, on utilise une approche manuelle) ===
def test_afroxlm_r():
    print("\n🔍 Testing AfroXLM-R...")
    model_name = "Davlan/afro-xlmr-large"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)

    def mean_pooling(model_output, attention_mask):
        token_embeddings = model_output.last_hidden_state
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    # Encodage des phrases
    def encode(text):
        inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=128)
        with torch.no_grad():
            outputs = model(**inputs)
        return mean_pooling(outputs, inputs['attention_mask']).squeeze(0).numpy()

    question_embed = encode(question)
    true_embed = encode(true_answer)
    false_embed = encode(false_answer)

    # Similarité cosinus
    sim_true = cosine_similarity([question_embed], [true_embed])[0][0]
    sim_false = cosine_similarity([question_embed], [false_embed])[0][0]

    print(f"✔️ Similarité avec la BONNE réponse : {sim_true:.4f}")
    print(f"❌ Similarité avec la FAUSSE réponse : {sim_false:.4f}")

# Lancement des tests
test_bge_m3()
test_afroxlm_r()

🔍 Testing BGE-M3...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

✔️ Similarité avec la BONNE réponse : 0.6825
❌ Similarité avec la FAUSSE réponse : 0.6429

🔍 Testing AfroXLM-R...

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/714 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of XLMRobertaModel were not initialized from the model checkpoint at Davlan/afro-xlmr-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✔️ Similarité avec la BONNE réponse : 0.7686
❌ Similarité avec la FAUSSE réponse : 0.8800

In [ ]:
# =================== 🔧 IMPORTS ===================
import os
import json
import torch
import random
import zipfile
from datetime import datetime
from sklearn.model_selection import train_test_split
from collections import defaultdict

from google.colab import drive
from sentence_transformers import (
    SentenceTransformer,
    InputExample,
    losses,
    evaluation,
    models,
    util
)
from sentence_transformers.datasets import NoDuplicatesDataLoader
from sentence_transformers.evaluation import SequentialEvaluator
from sentence_transformers.util import cos_sim
from torch.utils.data.sampler import BatchSampler, RandomSampler
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import DataLoader
# =================== 📂 CONFIGURATION ===================

MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
BATCH_SIZE = 32
EPOCHS_PHASE1 = 3  # Nombre d'époques pour la phase monolingue
EPOCHS_PHASE2 = 3  # Nombre d'époques pour la phase cross-lingue
LR_PHASE1 = 2e-5
LR_PHASE2 = 5e-6
WARMUP_STEPS = 100
EARLY_STOPPING_PATIENCE = 2
EARLY_STOPPING_MIN_DELTA = 0.01

# Chemins des fichiers
TRIPLET_ZIP_PATH = "/content/drive/MyDrive/culture_donnees_sur_drive_sans_variance.zip"
EXTRACT_DIR = "/content/triplet_data"
SAVE_DIR = "./fine_tuned_model_bambara"
LANGUES_ACCEPTEES = {'français', 'bambara'}

from huggingface_hub import notebook_login
notebook_login()
# =================== 🔗 MONTAGE GOOGLE DRIVE ===================
print("🚀 Montage de Google Drive...")
drive.mount('/content/drive')

# =================== 🎮 CONFIGURATION GPU ===================
print("\n🔍 Vérification de la disponibilité du GPU...")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device utilisé: {device}")
if device.type == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Capabilité CUDA: {torch.cuda.get_device_capability(0)}")
    print(f"Mémoire disponible: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} Go")


# =================== 🔧 CONFIGURATION INITIALE ===================
import os
# Désactive complètement Weights & Biases
os.environ["WANDB_DISABLED"] = "true"

# =================== 📦 EXTRACTION DU ZIP ===================
print("📁 Extraction des données du fichier zip...")
os.makedirs(EXTRACT_DIR, exist_ok=True)
with zipfile.ZipFile(TRIPLET_ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_DIR)

# Mettre à jour le chemin vers le fichier JSON une fois extrait
TRIPLETS_PATH = os.path.join(EXTRACT_DIR, 'culture_donnees_sur_drive_sans_variance.json')

# =================== 📚 CHARGEMENT ET NETTOYAGE DES TRIPLETS ===================
def load_and_clean_triplets(filepath):
    """
    Charge les triplets depuis un fichier JSON, nettoie le texte,
    supprime les triplets dupliqués exacts et valide la structure.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    cleaned = []
    seen = set()
    id_counts = defaultdict(int)

    required_keys = {'anchor', 'positive', 'negative', 'langue'}
    optional_keys = {'positive_langue', 'id', 'niveau', 'matiere', 'negative_type'}

    for idx, t in enumerate(raw_data):
        # Validation des champs obligatoires
        if not all(k in t for k in required_keys):
            print(f"⚠️ Triplet incomplet ignoré (ligne {idx}): {t.get('id', 'sans ID')}")
            continue

        # Nettoyage des textes
        anchor = t['anchor'].strip()
        positive = t['positive'].strip()
        negative = t['negative'].strip()
        langue = t['langue'].lower()
        positive_langue = t.get("positive_langue", langue).lower()

        # Validation des langues
        if langue not in LANGUES_ACCEPTEES or positive_langue not in LANGUES_ACCEPTEES:
            print(f"🚫 Langue non acceptée - Anchor: {langue}, Positive: {positive_langue}")
            continue

        # Génération d'un ID unique si non fourni
        if 'id' not in t:
            base_id = f"{t.get('matiere', 'GEN')}_{langue[:2]}_{idx}"
            t['id'] = base_id

        # Comptage des IDs pour détecter les doublons
        id_counts[t['id']] += 1
        if id_counts[t['id']] > 1:
            t['id'] = f"{t['id']}_{id_counts[t['id']]}"

        # Création d'une signature unique pour détecter les doublons
        content_key = (anchor[:100], positive[:100], negative[:100], langue, positive_langue)

        if content_key not in seen:
            seen.add(content_key)
            cleaned.append({
                'id': t['id'],
                'anchor': anchor,
                'positive': positive,
                'negative': negative,
                'langue': langue,
                'positive_langue': positive_langue,
                'niveau': t.get('niveau'),
                'matiere': t.get('matiere'),
                'negative_type': t.get('negative_type')
            })
        else:
            print(f"🚫 Doublon détecté - ID: {t['id']}")

    print(f"\n✔️ {len(cleaned)} triplets uniques et valides chargés.")
    print(f"📊 Répartition par langue:")
    for lang in LANGUES_ACCEPTEES:
        count = sum(1 for t in cleaned if t['langue'] == lang)
        print(f"  - {lang.capitalize()}: {count} triplets")

    return cleaned

# =================== 🧪 DATASET SPLIT (MONOLINGUE / CROSS-LANGUE) ===================
def split_data(triplets):
    """
    Sépare les triplets en ensembles monolingues (Phase 1) et cross-lingues (Phase 2).
    """
    phase1 = []  # Triplés où anchor_langue == positive_langue
    phase2 = []  # Triplés où anchor_langue != positive_langue

    for t in triplets:
        if t["langue"] == t["positive_langue"]:
            phase1.append(t)
        else:
            phase2.append(t)

    print(f"\n📊 Division des données:")
    print(f"  - Phase 1 (monolingue): {len(phase1)} triplets")
    print(f"  - Phase 2 (cross-lingue): {len(phase2)} triplets")

    # Statistiques supplémentaires
    if phase1:
        print("\n🔵 Phase 1 - Répartition:")
        for lang in LANGUES_ACCEPTEES:
            count = sum(1 for t in phase1 if t['langue'] == lang)
            print(f"  - {lang.capitalize()}: {count} triplets")

    if phase2:
        print("\n🟣 Phase 2 - Paires linguistiques:")
        cross_pairs = set((t['langue'], t['positive_langue']) for t in phase2)
        for pair in cross_pairs:
            count = sum(1 for t in phase2 if t['langue'] == pair[0] and t['positive_langue'] == pair[1])
            print(f"  - {pair[0]} → {pair[1]}: {count} triplets")

    return phase1, phase2

# =================== 📝 CONVERSION EN INPUTEXAMPLES ===================
def to_input_examples(triplets_list):
    """Convertit une liste de dictionnaires triplets en objets InputExample."""
    examples = []
    for t in triplets_list:
        # Validation de la longueur des textes
        if len(t["anchor"]) < 5 or len(t["positive"]) < 5 or len(t["negative"]) < 5:
            print(f"⚠️ Texte trop court ignoré - ID: {t['id']}")
            continue
        examples.append(InputExample(
            texts=[t["anchor"], t["positive"], t["negative"]],
            label=1.0  # Label fixe pour les triplets
        ))
    return examples

# =================== ⚙️ LOSS FUNCTIONS CUSTOMISÉES ===================
class DynamicTripletLoss(losses.TripletLoss):
    """
    Triplet Loss avec une marge dynamique basée sur la difficulté des exemples.
    """
    def __init__(self, model, **kwargs):
        super().__init__(model, **kwargs)
        self.min_margin = 0.2
        self.max_margin = 0.8
        self.margin_history = []

    def forward(self, sentence_features, labels):
        # Calcul des embeddings
        embeddings = [self.model(sf)['sentence_embedding'] for sf in sentence_features]
        anchor, positive, negative = embeddings

        # Calcul des similarités
        sim_pos = cos_sim(anchor, positive)
        sim_neg = cos_sim(anchor, negative)

        # Ajustement dynamique de la marge
        current_diff = (sim_neg - sim_pos).mean().item()
        dynamic_margin = min(max(current_diff, self.min_margin), self.max_margin)
        self.triplet_margin = dynamic_margin
        self.margin_history.append(dynamic_margin)

        # Calcul de la perte avec la marge dynamique
        loss = torch.relu(sim_pos - sim_neg + dynamic_margin)
        return loss.mean()

class AlignedCombinedLoss(torch.nn.Module):
    """
    Combine TripletLoss, MultipleNegativesRankingLoss et un terme d'alignement cross-lingue.
    """
    def __init__(self, model, triplet_weight=1.0, mnr_weight=0.5, align_weight=0.3):
        super().__init__()
        self.model = model
        self.triplet = DynamicTripletLoss(model=model)
        self.mnr = losses.MultipleNegativesRankingLoss(model=model)
        self.triplet_weight = triplet_weight
        self.mnr_weight = mnr_weight
        self.align_weight = align_weight

    def forward(self, sentence_features, labels):
        # Calcul des embeddings
        embeddings = [self.model(sf)['sentence_embedding'] for sf in sentence_features]
        anchor, positive, negative = embeddings

        # Calcul des différentes pertes
        triplet_loss = self.triplet(sentence_features, labels)

        # MNR Loss nécessite une reformulation des données
        mnr_features = [{'sentence_embedding': anchor}, {'sentence_embedding': positive}]
        mnr_loss = self.mnr(mnr_features, labels)

        # Perte d'alignement cross-lingue
        align_loss = 1 - cos_sim(anchor, positive).mean()

        # Combinaison pondérée
        total_loss = (self.triplet_weight * triplet_loss +
                     self.mnr_weight * mnr_loss +
                     self.align_weight * align_loss)

        # Monitoring (pour debug)
        if random.random() < 0.01:  # Log 1% des batches
            print(f"\n🔍 Monitoring des pertes:")
            print(f"  - Triplet: {triplet_loss.item():.4f} (marge: {self.triplet.triplet_margin:.3f})")
            print(f"  - MNR: {mnr_loss.item():.4f}")
            print(f"  - Alignement: {align_loss.item():.4f}")
            print(f"  → Total: {total_loss.item():.4f}")

        return total_loss

# =================== 📊 ÉVALUATEURS ROBUSTES ===================
def build_evaluation_sets():
    """Construit des ensembles de test pour l'évaluation."""
    # Exemples de requêtes et corpus pour chaque langue
    queries = {
        "fr": [
            "Quelle est la boisson chaude emblématique de l'hospitalité malienne ?",
            "Comment s'appelle le vêtement traditionnel porté au Mali ?",
            "Quel est le rôle du cerveau dans la motricité ?",
            "Définissez une tempête de sable."
        ],
        "bm": [
            "Mali faso minfɛn ye jumɛn ye, min bɛ sɔrɔ seli bɛɛ la?",
            "Mali laadala fini min ka bon ani min ɲɛw ye bulama ye, an b'o wele cogo di?",
            "Hakili bɛ an ka lamaga-lamagaliw kɔlɔsi cogo di?",
            "Cɛɲi ye mun ye?"
        ]
    }

    corpus = {
        "fr": [
            "Le thé vert, appelé 'ataya', est la boisson la plus consommée au Mali et symbolise l'hospitalité.",
            "Le boubou est le vêtement traditionnel malien, porté en toutes occasions par les hommes et les femmes.",
            "Le cerveau contrôle les mouvements volontaires et involontaires via le cortex moteur et le cervelet.",
            "Une tempête de sable est un phénomène météorologique avec des vents forts transportant du sable."
        ],
        "bm": [
            "Te wuluwulu, n'a bɛ fɔ a ma ko 'ataya', ye Mali ka minfɛn ye min bɛ ji caman ye, ani a bɛ jira bonya ni hakili la.",
            "Boubou ye Mali laadala fini ye, min bɛ fɛnw caya ani min bɛ fɛnw caya.",
            "Sugunɛ, ani n'a fɔra ka ɲɛ, farikolo-ɲɛnajɛ-yɔrɔ ni kunsɛmɛ, jɔyɔrɔ ka bon kosɛbɛ ŋaniyajira ni ŋaniyabaliya lamaga-lamagaliw kɔlɔsili la.",
            "Cɛɲi ye waati ye min na fiɲɛba bɛ cɛncɛn ni buguri camanba lawuli ka bɔ duguma."
        ]
    }

    # Documents pertinents pour chaque requête (dans les deux langues)
    relevant_docs = {
        # Requêtes françaises
        queries["fr"][0]: [corpus["fr"][0], corpus["bm"][0]],
        queries["fr"][1]: [corpus["fr"][1], corpus["bm"][1]],
        queries["fr"][2]: [corpus["fr"][2], corpus["bm"][2]],
        queries["fr"][3]: [corpus["fr"][3], corpus["bm"][3]],
        # Requêtes bambara
        queries["bm"][0]: [corpus["fr"][0], corpus["bm"][0]],
        queries["bm"][1]: [corpus["fr"][1], corpus["bm"][1]],
        queries["bm"][2]: [corpus["fr"][2], corpus["bm"][2]],
        queries["bm"][3]: [corpus["fr"][3], corpus["bm"][3]]
    }

    # Création des dictionnaires nécessaires pour les évaluateurs
    corpus_dict = {f"fr_{i}": text for i, text in enumerate(corpus["fr"])}
    corpus_dict.update({f"bm_{i}": text for i, text in enumerate(corpus["bm"])})

    relevant_docs_mapped = {}
    for q_text, docs in relevant_docs.items():
        relevant_docs_mapped[q_text] = []
        for doc in docs:
            for doc_id, text in corpus_dict.items():
                if text == doc:
                    relevant_docs_mapped[q_text].append(doc_id)
                    break

    return queries, corpus_dict, relevant_docs_mapped

def build_robust_evaluators():
    """Construit plusieurs évaluateurs pour un suivi complet."""
    queries, corpus, relevant_docs = build_evaluation_sets()

    # Évaluateur monolingue français
    eval_fr = evaluation.InformationRetrievalEvaluator(
        queries["fr"],
        {k: v for k, v in corpus.items() if k.startswith('fr_')},
        {k: [d for d in v if d.startswith('fr_')]
         for k, v in relevant_docs.items() if k in queries["fr"]},
        name="French Monolingual",
        show_progress_bar=False
    )

    # Évaluateur monolingue bambara
    eval_bm = evaluation.InformationRetrievalEvaluator(
        queries["bm"],
        {k: v for k, v in corpus.items() if k.startswith('bm_')},
        {k: [d for d in v if d.startswith('bm_')]
         for k, v in relevant_docs.items() if k in queries["bm"]},
        name="Bambara Monolingual",
        show_progress_bar=False
    )

    # Évaluateur cross-lingue complet
    eval_cross = evaluation.InformationRetrievalEvaluator(
        queries["fr"] + queries["bm"],
        corpus,
        relevant_docs,
        name="Cross-lingual",
        show_progress_bar=False
    )

    # Évaluateur séquentiel combinant les trois
    return SequentialEvaluator([eval_fr, eval_bm, eval_cross])

# =================== 🏋️ DATALOADERS ÉQUILIBRÉS ===================
class BalancedTripletSampler:
    """Garantit un équilibre des langues dans chaque batch."""
    def __init__(self, triplets, batch_size):
        self.triplets = triplets
        self.batch_size = batch_size
        self.lang_indices = {
            lang: [i for i, t in enumerate(triplets) if t['langue'] == lang]
            for lang in LANGUES_ACCEPTEES
        }

    def __iter__(self):
        # Mélanger les indices pour chaque langue
        for lang in self.lang_indices:
            random.shuffle(self.lang_indices[lang])

        # Calculer le nombre de batches complets possibles
        min_samples = min(len(indices) for indices in self.lang_indices.values())
        num_batches = min_samples // (self.batch_size // len(LANGUES_ACCEPTEES))

        # Générer des batches équilibrés
        for i in range(num_batches):
            batch = []
            for lang in self.lang_indices:
                start = i * (self.batch_size // len(LANGUES_ACCEPTEES))
                end = start + (self.batch_size // len(LANGUES_ACCEPTEES))
                batch.extend(self.lang_indices[lang][start:end])

            random.shuffle(batch)
            yield batch

    def __len__(self):
        min_samples = min(len(indices) for indices in self.lang_indices.values())
        return min_samples // (self.batch_size // len(LANGUES_ACCEPTEES))

def create_balanced_dataloader(triplets, examples, batch_size, phase_name):
    """Crée un DataLoader équilibré selon la phase d'entraînement."""
    if phase_name == "monolingual":
        # Pour la phase monolingue, nous voulons des batches mixtes français/bambara
        sampler = BalancedTripletSampler(triplets, batch_size)
        return DataLoader(
            examples,
            batch_sampler=BatchSampler(sampler, batch_size=batch_size, drop_last=False),
            shuffle=False
        )
    else:
        # Pour la phase cross-lingue, nous utilisons NoDuplicatesDataLoader standard
        return NoDuplicatesDataLoader(examples, batch_size=batch_size)

# =================== 🏁 FONCTION D'ENTRAÎNEMENT ===================
def fit_phase(model, dataloader, triplets, epochs, lr, phase_name, evaluator):
    """
    Fonction complète pour entraîner le modèle sur une phase donnée.
    """
    print(f"\n🏁 Début de la phase {phase_name}...")
    print(f"  - Nombre de batches par epoch: {len(dataloader)}")
    print(f"  - Taille des batches: {dataloader.batch_size}")
    print(f"  - Nombre d'époques: {epochs}")
    print(f"  - Taux d'apprentissage: {lr:.1e}")

    # Optimizer et scheduler
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=WARMUP_STEPS,
        num_training_steps=epochs * len(dataloader)
    )

    # Configuration de l'early stopping
    early_stopping = evaluation.EarlyStopping(
        checkpoint_path=os.path.join(SAVE_DIR, f"best_{phase_name}"),
        patience=EARLY_STOPPING_PATIENCE,
        min_delta=EARLY_STOPPING_MIN_DELTA,
        max_epochs=epochs
    )

    # Configuration de la perte
    if phase_name == "monolingual":
        loss_model = AlignedCombinedLoss(model, triplet_weight=1.0, mnr_weight=0.5, align_weight=0.0)
    else:
        loss_model = AlignedCombinedLoss(model, triplet_weight=1.0, mnr_weight=0.3, align_weight=0.3)

    # Entraînement
    model.fit(
        train_objectives=[(dataloader, loss_model)],
        epochs=epochs,
        warmup_steps=WARMUP_STEPS,
        optimizer=optimizer,
        scheduler=scheduler,
        evaluator=evaluator,
        evaluation_steps=max(50, len(dataloader)//5),  # Évaluer 5 fois par epoch
        output_path=os.path.join(SAVE_DIR, phase_name),
        save_best_model=True,
        use_amp=True,
        show_progress_bar=True,
        callback=[early_stopping]
    )

    print(f"✅ Phase {phase_name} terminée. Meilleur modèle sauvegardé.")

# =================== 🧪 TESTS FINAUX ===================
def run_final_tests(model):
    """Exécute une batterie de tests finaux sur le modèle entraîné."""
    print("\n🔬 Lancement des tests finaux...")

    # Test d'alignement cross-lingue
    print("\n🔍 Test d'alignement cross-lingue:")
    test_pairs = [
        ("Le thé malien est très populaire.", "Te Mali ka ka bon kosɛbɛ."),
        ("Le boubou est un vêtement traditionnel élégant.", "Boubou ye fini laadala ye min ka ɲi."),
        ("La capitale du Mali est Bamako.", "Mali faaba ye Bamako ye."),
        ("Comment dit-on 'bonjour' en bambara ?", "I ni ce kɛlɛbɛ la min bɛ fɔ bambara kan na?")
    ]

    for fr, bm in test_pairs:
        fr_emb = model.encode(fr, convert_to_tensor=True)
        bm_emb = model.encode(bm, convert_to_tensor=True)
        sim = cos_sim(fr_emb, bm_emb).item()
        print(f"  {fr[:30]}... ↔ {bm[:30]}...: {sim:.4f}")

    # Test de similarité monolingue
    print("\n🔍 Test de similarité monolingue:")
    fr_pairs = [
        ("Le thé malien est délicieux.", "L'ataya est une boisson populaire au Mali."),
        ("Le boubou est un vêtement ample.", "Les Maliens portent des vêtements traditionnels.")
    ]

    for a, b in fr_pairs:
        a_emb = model.encode(a, convert_to_tensor=True)
        b_emb = model.encode(b, convert_to_tensor=True)
        sim = cos_sim(a_emb, b_emb).item()
        print(f"  {a[:30]}... ↔ {b[:30]}...: {sim:.4f}")

    bm_pairs = [
        ("Te Mali ka di.", "Ataya ye minfɛn ye min bɛ Mali la."),
        ("Boubou ye fini dɔ ye.", "Mali denw bɛ fini caman wɛrɛw sɔrɔ.")
    ]

    for a, b in bm_pairs:
        a_emb = model.encode(a, convert_to_tensor=True)
        b_emb = model.encode(b, convert_to_tensor=True)
        sim = cos_sim(a_emb, b_emb).item()
        print(f"  {a[:30]}... ↔ {b[:30]}...: {sim:.4f}")

# =================== 🚀 PIPELINE PRINCIPAL ===================
def main():
    # Initialisation
    os.makedirs(SAVE_DIR, exist_ok=True)
    print("\n" + "="*50)
    print("🚀 INITIALISATION DU FINE-TUNING MULTILINGUE")
    print("="*50)

    # 1. Chargement et préparation des données
    print("\n📦 CHARGEMENT ET PRÉPARATION DES DONNÉES")
    triplets = load_and_clean_triplets(TRIPLETS_PATH)
    phase1_triplets, phase2_triplets = split_data(triplets)

    # 2. Conversion en InputExamples
    phase1_examples = to_input_examples(phase1_triplets)
    phase2_examples = to_input_examples(phase2_triplets)

    # 3. Création des DataLoaders équilibrés
    print("\n⚖️ CRÉATION DES DATALOADERS ÉQUILIBRÉS")
    dataloader1 = create_balanced_dataloader(phase1_triplets, phase1_examples, BATCH_SIZE, "monolingual")
    dataloader2 = create_balanced_dataloader(phase2_triplets, phase2_examples, BATCH_SIZE, "crosslingual")

    # 4. Initialisation du modèle
    print("\n🔄 CHARGEMENT DU MODÈLE DE BASE")
    word_embed = models.Transformer(MODEL_NAME)
    pooling = models.Pooling(word_embed.get_word_embedding_dimension(), 'cls')
    model = SentenceTransformer(modules=[word_embed, pooling])

    # Déplacer le modèle sur le GPU si disponible
    model.to(device)
    print(f"Modèle chargé: {MODEL_NAME}")
    print(f"Device utilisé: {next(model.parameters()).device}")
    print(f"Dimension des embeddings: {model.get_sentence_embedding_dimension()}")

    # 5. Préparation des évaluateurs
    evaluator = build_robust_evaluators()

    # 6. Phase 1 - Entraînement monolingue
    print("\n" + "="*50)
    print("🔵 PHASE 1 - ENTRAÎNEMENT MONOLINGUE")
    print("="*50)
    fit_phase(model, dataloader1, phase1_triplets, EPOCHS_PHASE1, LR_PHASE1, "phase1_monolingual", evaluator)

    # 7. Phase 2 - Entraînement cross-lingue
    print("\n" + "="*50)
    print("🟣 PHASE 2 - ENTRAÎNEMENT CROSS-LINGUE")
    print("="*50)
    fit_phase(model, dataloader2, phase2_triplets, EPOCHS_PHASE2, LR_PHASE2, "phase2_crosslingual", evaluator)

    # 8. Tests finaux
    print("\n" + "="*50)
    print("🧪 TESTS FINAUX")
    print("="*50)
    run_final_tests(model)

    # 9. Sauvegarde finale
    final_path = os.path.join(SAVE_DIR, "final_model")
    model.save(final_path)
    print(f"\n✅ ENTRAÎNEMENT TERMINÉ. Modèle final sauvegardé dans: {final_path}")

if __name__ == "__main__":
    main()

In [ ]:
import os
import json
import zipfile
import random
from datasets import Dataset
from transformers import EarlyStoppingCallback
from sentence_transformers import SentenceTransformer, losses, util, evaluation
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments

# ========== CONFIG ==========
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
TRIPLETS_ZIP_PATH = "/content/drive/MyDrive/culture_donnees_sur_drive_sans_variance.zip"
SAVE_DIR = "./fine_tuned_model_bambara"
os.makedirs(SAVE_DIR, exist_ok=True)

BATCH_SIZE = 16
EPOCHS_PHASE1 = 10  # Augmenté pour permettre un meilleur apprentissage
EPOCHS_PHASE2 = 8
LR_PHASE1 = 2e-5    # Learning rate légèrement augmenté
LR_PHASE2 = 1e-5
MIN_DELTA = 0.0001  # Plus sensible pour détecter les améliorations

# ========== DATA AUGMENTATION ==========
def augment_triplet(triplet):
    """Simple data augmentation for text triplets"""
    augmented = triplet.copy()

    # Random word deletion (10% chance per word)
    for field in ['anchor', 'positive', 'negative']:
        words = triplet[field].split()
        if len(words) > 3 and random.random() < 0.3:
            del_idx = random.randint(0, len(words)-1)
            words.pop(del_idx)
            augmented[field] = ' '.join(words)

    # Synonym replacement (simplified example)
    replacements = {
        'bonjour': ['salam', 'aw ni sogoma'],
        'merci': ['a ni ce', 'i ni ce']
    }

    for field in ['anchor', 'positive', 'negative']:
        for word, syns in replacements.items():
            if word in triplet[field]:
                augmented[field] = augmented[field].replace(word, random.choice(syns))

    return augmented

# ========== ENHANCED EVALUATOR ==========
def build_robust_evaluator(dataset, num_samples=200):
    """Build evaluator with proper train/test split"""
    # Sample evaluation data
    eval_samples = dataset.shuffle().select(range(min(num_samples, len(dataset))))

    queries = {}
    corpus = {}
    relevant_docs = {}

    for idx, sample in enumerate(eval_samples):
        queries[idx] = sample['anchor']
        corpus[2*idx] = sample['positive']
        corpus[2*idx+1] = sample['negative']
        relevant_docs[idx] = [2*idx]  # Only positive is relevant

    return evaluation.InformationRetrievalEvaluator(
        queries, corpus, relevant_docs,
        show_progress_bar=True,
        corpus_chunk_size=512,
        precision_recall_at_k=[3, 5, 10],
        name='bambara_eval'
    )

# ========== IMPROVED DATA LOADING ==========
def load_and_prepare_data():
    with zipfile.ZipFile(TRIPLETS_ZIP_PATH, 'r') as z:
        with z.open(z.namelist()[0]) as f:
            data = json.load(f)

    # Apply simple data augmentation
    augmented_data = []
    for item in data:
        augmented_data.append(item)
        # Add 1 augmented version for each original triplet (50% increase)
        if random.random() < 0.5:
            augmented_data.append(augment_triplet(item))

    # Split into phases with 80/20 train/val split
    random.shuffle(augmented_data)
    split_idx = int(0.8 * len(augmented_data))

    phase1_data, phase2_data = [], []
    for item in augmented_data[:split_idx]:  # Training data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            phase1_data.append(record)
        else:
            phase2_data.append(record)

    # Create validation sets
    val_phase1, val_phase2 = [], []
    for item in augmented_data[split_idx:]:  # Validation data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            val_phase1.append(record)
        else:
            val_phase2.append(record)

    return (
        Dataset.from_list(phase1_data),
        Dataset.from_list(val_phase1),
        Dataset.from_list(phase2_data),
        Dataset.from_list(val_phase2)
    )

# ========== ENHANCED TRAINING PHASE ==========
def train_phase(model, train_data, val_data, epochs, lr, phase_name):
    # Use multiple negative ranking loss for better convergence
    loss = losses.MultipleNegativesRankingLoss(model)

    # Create robust evaluator
    evaluator = build_robust_evaluator(val_data)

    # Enhanced training arguments
    training_args = SentenceTransformerTrainingArguments(
        output_dir=os.path.join(SAVE_DIR, phase_name),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE*2,
        num_train_epochs=epochs,
        learning_rate=lr,
        weight_decay=0.01,  # Added regularization
        warmup_ratio=0.1,   # Better learning rate scheduling
        # evaluation_strategy="steps",
        eval_strategy="steps",
        logging_strategy="steps",
        eval_steps=100,
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_bambara_eval_cosine_ndcg@10",
        greater_is_better=True,
        logging_dir=os.path.join(SAVE_DIR, "logs"),
        logging_steps=50,
        report_to=[],
        fp16=True  # Enable mixed precision training
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        loss=loss,
        evaluator=evaluator,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3,
                early_stopping_threshold=MIN_DELTA
            )
        ],
    )

    print(f"\n⭐ Starting {phase_name} training with {len(train_data)} samples")
    trainer.train()

    # Final evaluation
    print("\n📊 Final evaluation results:")
    evaluator(model)

    model.save(os.path.join(SAVE_DIR, f"{phase_name}_final"))
    return model

# ========== MAIN ==========
def main():
    # Load model with better tokenizer handling
    model = SentenceTransformer(MODEL_NAME)
    print("Model loaded with {} parameters".format(sum(p.numel() for p in model.parameters())))

    # Load and split data
    phase1_train, phase1_val, phase2_train, phase2_val = load_and_prepare_data()
    print(f"\nData loaded: {len(phase1_train)} phase1 train, {len(phase1_val)} phase1 val, "
          f"{len(phase2_train)} phase2 train, {len(phase2_val)} phase2 val samples")

    # Phase 1: Monolingual fine-tuning
    print("\n🔵 Phase 1: Monolingual Fine-tuning")
    model = train_phase(
        model, phase1_train, phase1_val,
        EPOCHS_PHASE1, LR_PHASE1, "phase1"
    )

    # Phase 2: Cross-lingual adaptation
    print("\n🟣 Phase 2: Cross-lingual Adaptation")
    model = train_phase(
        model, phase2_train, phase2_val,
        EPOCHS_PHASE2, LR_PHASE2, "phase2"
    )

    # Final save with better metadata
    model.save(os.path.join(SAVE_DIR, "final_model_bambara"))
    print("\n✅ Training completed successfully!")

    # Test some examples
    test_queries = [
        ("Bonjour comment ça va?", "I ni sogoma, i ka kɛnɛ wa?"),
        ("Quelle est la capitale du Mali?", "Mali faaba ye mun ye?")
    ]
    for q1, q2 in test_queries:
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        sim = util.cos_sim(emb1, emb2).item()
        print(f"Similarity between '{q1}' and '{q2}': {sim:.4f}")

if __name__ == "__main__":
    main()

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Model loaded with 278043648 parameters

Data loaded: 3247 phase1 train, 822 phase1 val, 3247 phase2 train, 802 phase2 val samples

🔵 Phase 1: Monolingual Fine-tuning

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

⭐ Starting phase1 training with 3247 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.98it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

🟣 Phase 2: Cross-lingual Adaptation

⭐ Starting phase2 training with 3247 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s]

KeyboardInterrupt:

In [ ]:
#  nous allons verifier les fragments fait par le tokenizer , voir si c'est catastrophique ou si nous devons modifier le tokenizer pour ajouter les mots les plus frequents en bambara
from transformers import EarlyStoppingCallback, Trainer, TrainingArguments
from sentence_transformers import SentenceTransformerTrainer
from sentence_transformers.losses import TripletLoss, MultipleNegativesRankingLoss

# ========== CONFIGURATION ==========
training_args = TrainingArguments(
    output_dir=SAVE_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS_PHASE1,
    learning_rate=LR_PHASE1,
    eval_strategy="steps",
    eval_steps=50,
    save_steps=50,
    warmup_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    fp16=True,
)

# ========== MODÈLE ET TOKENIZER ==========
model = SentenceTransformer(MODEL_NAME)
model = prepare_tokenizer(model)  # Votre fonction existante

# ========== LOSS COMBINÉE ==========
class CombinedLoss(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.triplet = TripletLoss(model=model)
        self.mnr = MultipleNegativesRankingLoss(model=model)

    def forward(self, features, labels):
        return self.triplet(features, labels) + self.mnr(features, labels)

# ========== ENTRAÎNEMENT ==========
def train_phase(model, dataloader, epochs, lr, phase_name):
    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=dataloader.dataset,
        eval_dataset=build_enhanced_evaluator().examples,
        compute_metrics=build_enhanced_evaluator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2, early_stopping_threshold=MIN_DELTA)],
        loss=CombinedLoss(model)
    )

    trainer.train()
    model.save(os.path.join(SAVE_DIR, phase_name))

# ========== UTILISATION ==========
def main():
    dataloader1, dataloader2 = load_data()

    print("\n🔵 Phase 1 : Monolingue")
    train_phase(model, dataloader1, EPOCHS_PHASE1, LR_PHASE1, "phase1")

    print("\n🟣 Phase 2 : Cross-lingue")
    training_args.learning_rate = LR_PHASE2
    training_args.num_train_epochs = EPOCHS_PHASE2
    train_phase(model, dataloader2, EPOCHS_PHASE2, LR_PHASE2, "phase2")

=== INITIALISATION DU TOKENIZER ===

=== AVANT AJOUT DES TOKENS ===

Phrase: 'ɲɛtaa sɔrɔ'
Tokenisation originale: ['▁', 'ɲ', 'ɛ', 'taa', '▁s', 'ɔ', 'r', 'ɔ']
IDs: [0, 6, 245963, 171522, 6803, 91, 184135, 42, 184135, 2]

Phrase: 'N ye fɔlɔ dɔnni sɔgɔma'
Tokenisation originale: ['▁N', '▁ye', '▁f', 'ɔ', 'l', 'ɔ', '▁d', 'ɔ', 'nni', '▁s', 'ɔ', 'g', 'ɔ', 'ma']
IDs: [0, 541, 2422, 1238, 184135, 141, 184135, 104, 184135, 10016, 91, 184135, 177, 184135, 192, 2]

Phrase: 'bamanankan kɛnɛ'
Tokenisation originale: ['▁ba', 'manan', 'kan', '▁k', 'ɛ', 'n', 'ɛ']
IDs: [0, 961, 95980, 331, 472, 171522, 19, 171522, 2]

=== AJOUT DES TOKENS BAMBARA ===

=== APRÈS AJOUT DES TOKENS ===

Phrase: 'ɲɛtaa sɔrɔ'
Nouvelle tokenisation: ['▁', 'ɲ', 'ɛ', 'taa', '▁s', 'ɔ', 'r', 'ɔ']
Nouveaux IDs: [0, 6, 245963, 171522, 6803, 91, 184135, 42, 184135, 2]
Décodage: <s> ɲɛtaa sɔrɔ</s>

Phrase: 'N ye fɔlɔ dɔnni sɔgɔma'
Nouvelle tokenisation: ['▁N', '▁ye', '▁f', 'ɔ', 'l', 'ɔ', '▁d', 'ɔ', 'nni', '▁s', 'ɔ', 'g', 'ɔ', 'ma']
Nouveaux IDs: [0, 541, 2422, 1238, 184135, 141, 184135, 104, 184135, 10016, 91, 184135, 177, 184135, 192, 2]
Décodage: <s> N ye fɔlɔ dɔnni sɔgɔma</s>

Phrase: 'bamanankan kɛnɛ'
Nouvelle tokenisation: ['▁ba', 'manan', 'kan', '▁k', 'ɛ', 'n', 'ɛ']
Nouveaux IDs: [0, 961, 95980, 331, 472, 171522, 19, 171522, 2]
Décodage: <s> bamanankan kɛnɛ</s>

=== VÉRIFICATION DES TOKENS ===
Token '_ɲɛ' présent? Oui
Token '_sɔrɔ' présent? Oui
Token '_fɔlɔ' présent? Oui
Token '_kɔrɔ' présent? Oui
Token '_ɲɛtaa' présent? Oui
Token '_bamanankan' présent? Oui
Token '_dɔnni' présent? Oui
Token '_dɛmɛ' présent? Oui
Token '_kɛnɛ' présent? Oui
Token '_sɔgɔma' présent? Oui

In [ ]:
# ici nous allons ajouter les mots les plus frequents de notre corpus bambara dans le tokenizer et refaire un entrainement pour voir si nous avons de meilleurs resultats
import os
import json
import zipfile
import random
from datasets import Dataset
from transformers import EarlyStoppingCallback
from sentence_transformers import SentenceTransformer, losses, util, evaluation
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments
from google.colab import drive

# ========== CONFIG ==========
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
TRIPLETS_ZIP_PATH = "/content/drive/MyDrive/culture_donnees_sur_drive_sans_variance.zip"
SAVE_DIR = "/content/drive/MyDrive/fine_tuned_model_bambara_fusion3"
os.makedirs(SAVE_DIR, exist_ok=True)

# Liste des tokens bambara à ajouter
BAMBARA_TOKENS = [
    "_tiɲɛ",
    "_bɔli",
    "_daɲɛw",
    "_jatigɛ",
    "_jɛkulu",
    "_kɛlɛ",
    "_kɛrɛnkɛrɛnnenya",
    "_yɔrɔ",
    "_baarakɛcogo",
    "_baarakɛlaw",
    "_baarakɛnafolo",
    "_balofɛn",
    "_balofɛnw",
    "_banakisɛ",
    "_banakisɛw",
    "_bolifɛnw",
    "_bololabaarakɛlaw",
    "_bɔ",
    "_bɔgɔ",
    "_bɔgɔdaga",
    "_bɔlen",
    "_bɔnsɔn",
    "_bɔnsɔnw",
    "_bɔnɛni",
    "_bɔra",
    "_bɔyɔrɔ",
    "_bɛ",
    "_bɛn",
    "_bɛna",
    "_bɛnbaliya",
    "_bɛnbaliyakow",
    "_bɛnbaw",
    "_bɛnkan",
    "_bɛnnen",
    "_bɛɛ",
    "_ciyɛn",
    "_cɛ",
    "_cɛfarinw",
    "_cɛma",
    "_cɛmancɛ",
    "_cɛsira",
    "_cɛsiri",
    "_cɛw",
    "_cɛɲi",
    "_dabɔ",
    "_dabɔli",
    "_dabɔra",
    "_dalajɛli",
    "_daminɛ",
    "_daminɛna",
    "_dancɛw",
    "_danfɛnw",
    "_dantigɛli",
    "_danyɔrɔ",
    "_daɲɛ",
    "_daɲɛgafe",
    "_denmisɛnw",
    "_diinɛ",
    "_diinɛko",
    "_diinɛw",
    "_diɲɛ",
    "_dumunikɛcogo",
    "_dumunikɛyɔrɔ",
    "_dɔ",
    "_dɔgɔya",
    "_dɔgɔyali",
    "_dɔn",
    "_dɔnbaliya",
    "_dɔnkili",
    "_dɔnkilida",
    "_dɔnkilidala",
    "_dɔnkiliw",
    "_dɔnko",
    "_dɔnkotigi",
    "_dɔnni",
    "_dɔnniya",
    "_dɔnniyaw",
    "_dɔnw",
    "_dɔrɔn",
    "_dɔw",
    "_dɔni",
    "_dɛmɛ",
    "_dɛsɛ",
    "_erɔpu",
    "_erɔpukaw",
    "_farikolojɔli",
    "_farikoloɲɛnajɛ",
    "_fasodenɲumanya",
    "_fiɲɛ",
    "_fiɲɛbɔlan",
    "_funankɛninw",
    "_furakɛli",
    "_fɔcogo",
    "_fɔli",
    "_fɔlifɛn",
    "_fɔlifɛnw",
    "_fɔlisen",
    "_fɔlɔ",
    "_fɛ",
    "_fɛn",
    "_fɛnba",
    "_fɛnkɔrɔw",
    "_fɛnw",
    "_fɛnɲɛnama",
    "_fɛnɲɛnamafagalan",
    "_fɛnɲɛnamafagalanw",
    "_fɛnɲɛnamaw",
    "_fɛɛrɛ",
    "_fɛɛrɛw",
    "_gɛlɛya",
    "_gɛlɛyabaw",
    "_gɛlɛyaw",
    "_hakilijagabɔ",
    "_hakɛ",
    "_hɔrɔnya",
    "_hɛrɛ",
    "_jagɛlɛya",
    "_jatebɔ",
    "_jateminɛ",
    "_jinɛw",
    "_jisigiyɔrɔw",
    "_jogoɲumanya",
    "_jumɛn",
    "_jɔ",
    "_jɔcogo",
    "_jɔlen",
    "_jɔli",
    "_jɔn",
    "_jɔnfeere",
    "_jɔnjɔn",
    "_jɔnjɔnw",
    "_jɔnw",
    "_jɔnya",
    "_jɔyɔrɔ",
    "_jɔyɔrɔw",
    "_jɛgɛ",
    "_jɛkafɔ",
    "_jɛkuluw",
    "_jɛlen",
    "_jɛman",
    "_jɛmukan",
    "_jɛnsɛn",
    "_jɛnsɛnni",
    "_jɛɲɔgɔnya",
    "_jɛɲɔgɔnyaw",
    "_kemikɛlifɛnw",
    "_kiritigɛ",
    "_kiritigɛlaw",
    "_kosɔn.",
    "_kosɛbɛ",
    "_kulɛri",
    "_kumaɲɔgɔnya",
    "_kunbɛnni",
    "_kɔ",
    "_kɔfɛ",
    "_kɔgɔji",
    "_kɔgɔjida",
    "_kɔkan",
    "_kɔkanna",
    "_kɔlɔlɔ",
    "_kɔlɔlɔw",
    "_kɔlɔsili",
    "_kɔnɔ",
    "_kɔnɔfɛnw",
    "_kɔnɔkow",
    "_kɔnɔna",
    "_kɔnɔw",
    "_kɔrɔ",
    "_kɔrɔfɔli",
    "_kɔrɔlen",
    "_kɔrɔnyanfan",
    "_kɔrɔw",
    "_kɔɲɔw",
    "_kɛ",
    "_kɛcogo",
    "_kɛlen",
    "_kɛlenw",
    "_kɛli",
    "_kɛlɛba",
    "_kɛlɛli",
    "_kɛlɛw",
    "_kɛmɛ",
    "_kɛnɛ",
    "_kɛnɛma",
    "_kɛnɛman",
    "_kɛnɛya",
    "_kɛnɛyako",
    "_kɛrɛnkɛrɛnnen",
    "_kɛrɛnkɛrɛnnenw",
    "_kɛwalew",
    "_laadalatɔn",
    "_laadalatɔnw",
    "_labɛn",
    "_labɛncogo",
    "_labɛnnen",
    "_labɛnni",
    "_lajɛ",
    "_lajɛba",
    "_lajɛlen",
    "_lakɔli",
    "_lamɛnbagaw",
    "_lamɛnni",
    "_lamɛnnikɛlaw",
    "_latigɛw",
    "_laɲini",
    "_maanafɔla",
    "_maanafɔlaw",
    "_masakɛ",
    "_maskɛw",
    "_minfɛn",
    "_minɛ",
    "_minɛni",
    "_minɛnw",
    "_misɛnninw",
    "_muɲuli",
    "_mɔgɔ",
    "_mɔgɔba",
    "_mɔgɔkɔrɔbaw",
    "_mɔgɔw",
    "_mɔni",
    "_nafabɔli",
    "_nakɔfɛnw",
    "_nbɛdaw",
    "_nisɔndiya",
    "_nɔba",
    "_nɔfɛkow",
    "_nɔgɔ",
    "_nɔgɔlenw",
    "_nɔgɔli",
    "_nɔgɔman",
    "_nɔgɔmanw",
    "_nɔgɔn",
    "_nɔgɔw",
    "_nɔgɔya",
    "_nɛgɛ",
    "_nɛgɛso",
    "_nɛgɛw",
    "_nɛnɛ",
    "_politikitɔnw",
    "_revolisiyɔn",
    "_sanfɛla",
    "_senfɛ",
    "_sigidamɔgɔw",
    "_sigiyɔrɔ",
    "_silamɛ",
    "_silamɛw",
    "_silamɛya",
    "_siniɲɛsigi",
    "_siratigɛ",
    "_siɲɛ",
    "_sunɔgɔ",
    "_sɔgɔsɔgɔninjɛ",
    "_sɔn",
    "_sɔngɔ",
    "_sɔrɔ",
    "_sɔrɔcogo",
    "_sɔrɔko",
    "_sɔrɔli",
    "_sɔrɔta",
    "_sɔrɔyɔrɔ",
    "_sɔsɔli",
    "_sɛbɛn",
    "_sɛbɛnni",
    "_sɛbɛnw",
    "_sɛgɛn",
    "_sɛgɛsɛgɛ",
    "_sɛgɛsɛgɛli",
    "_sɛmɛntiya",
    "_sɛnɛ",
    "_sɛnɛfɛnw",
    "_sɛnɛkɛlaw",
    "_taamasiyɛn",
    "_taamasiyɛnw",
    "_taamasiɲɛw",
    "_taamasyɛn",
    "_tigɛ",
    "_tilancɛ",
    "_tiɲɛni",
    "_tiɲɛw",
    "_tɔgɔ",
    "_tɔgɔba",
    "_tɔnɔ",
    "_to",
    "_tɔw",
    "_tɔɔrɔ",
    "_tɛ",
    "_tɛmɛ",
    "_tɛmɛnen",
    "_tɛmɛsira",
    "_waleɲumandɔn",
    "_wɛrɛ",
    "_wɛrɛw",
    "_yɔrɔba",
    "_yɔrɔw",
    "_yɛrɛ",
    "_yɛrɛdɔn",
    "_yɛrɛmahɔrɔnya",
    "_yɛrɛmahɔrɔnyalen",
    "_ɔwɔ,",
    "_ɛndujamana",
    "_ɲagami",
    "_ɲagaminen",
    "_ɲi",
    "_ɲini",
    "_ɲinini",
    "_ɲininkali",
    "_ɲinw",
    "_ɲuman",
    "_ɲumanw",
    "_ɲɔgɔn",
    "_ɲɔgɔndan",
    "_ɲɔgɔndɛmɛ",
    "_ɲɔgɔnna",
    "_ɲɛ",
    "_ɲɛda",
    "_ɲɛfɔ",
    "_ɲɛfɔli",
    "_ɲɛgɛnw",
    "_ɲɛjirali",
    "_ɲɛmaa",
    "_ɲɛminɛ",
    "_ɲɛmɔgɔ",
    "_ɲɛmɔgɔw",
    "_ɲɛmɔgɔya",
    "_ɲɛnabɔ",
    "_ɲɛnabɔli",
    "_ɲɛnajɛ",
    "_ɲɛnajɛlamɔgɔw",
    "_ɲɛnama",
    "_ɲɛnamaya",
    "_ɲɛsin",
    "_ɲɛsinnen",
    "_ɲɛtaa",
]

BATCH_SIZE = 16
EPOCHS_PHASE1 = 10
EPOCHS_PHASE2 = 8
LR_PHASE1 = 2e-5
LR_PHASE2 = 1e-5
MIN_DELTA = 0.0001

# Montage Google Drive
print("🚀 Montage de Google Drive...")
drive.mount('/content/drive')

# ========== DATA AUGMENTATION ==========
def augment_triplet(triplet):
    """Simple data augmentation for text triplets"""
    augmented = triplet.copy()

    # Random word deletion (10% chance per word)
    for field in ['anchor', 'positive', 'negative']:
        words = triplet[field].split()
        if len(words) > 3 and random.random() < 0.3:
            del_idx = random.randint(0, len(words)-1)
            words.pop(del_idx)
            augmented[field] = ' '.join(words)

    # Synonym replacement (simplified example)
    replacements = {
         # Histoire/Culture
        'griot': ['jeli', 'djéli', 'àkòdànwò'],
        'histoire': ['tariku', 'lisite'],
        'empire': ['mansaya', 'sultani'],
        # Géographie
        'fleuve': ['ba', 'jiba'],
        'capitale': ['faaba', 'duguba'],
        'ville': ['dugu', 'sugo'],
        # Mathématiques
        'calculer': ['sanya', 'kalikuli'],
        'nombre': ['dɔgɔkun', 'nimɔrɔ'],
        'addition': ['fara', 'adision'],
        # Culture générale
        'cérémonie': ['seli', 'ɲɛnajɛ'],
        'tambour': ['dunun', 'tama']
    }

    for field in ['anchor', 'positive', 'negative']:
        for word, syns in replacements.items():
            if word in triplet[field]:
                augmented[field] = augmented[field].replace(word, random.choice(syns))

    return augmented

# ========== ENHANCED EVALUATOR ==========
def build_robust_evaluator(dataset, num_samples=200):
    """Build evaluator with proper train/test split"""
    # Sample evaluation data
    eval_samples = dataset.shuffle().select(range(min(num_samples, len(dataset))))

    queries = {}
    corpus = {}
    relevant_docs = {}

    for idx, sample in enumerate(eval_samples):
        queries[idx] = sample['anchor']
        corpus[2*idx] = sample['positive']
        corpus[2*idx+1] = sample['negative']
        relevant_docs[idx] = [2*idx]  # Only positive is relevant

    return evaluation.InformationRetrievalEvaluator(
        queries, corpus, relevant_docs,
        show_progress_bar=True,
        corpus_chunk_size=512,
        precision_recall_at_k=[3, 5, 10],
        name='bambara_eval'
    )

# ========== IMPROVED DATA LOADING ==========
def load_and_prepare_data():
    with zipfile.ZipFile(TRIPLETS_ZIP_PATH, 'r') as z:
        with z.open(z.namelist()[0]) as f:
            data = json.load(f)

    # Apply simple data augmentation
    augmented_data = []
    for item in data:
        augmented_data.append(item)
        # Add 1 augmented version for each original triplet (50% increase)
        if random.random() < 0.5:
            augmented_data.append(augment_triplet(item))

    # Split into phases with 80/20 train/val split
    random.shuffle(augmented_data)
    split_idx = int(0.8 * len(augmented_data))

    phase1_data, phase2_data = [], []
    for item in augmented_data[:split_idx]:  # Training data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            phase1_data.append(record)
        else:
            phase2_data.append(record)

    # Create validation sets
    val_phase1, val_phase2 = [], []
    for item in augmented_data[split_idx:]:  # Validation data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            val_phase1.append(record)
        else:
            val_phase2.append(record)

    return (
        Dataset.from_list(phase1_data),
        Dataset.from_list(val_phase1),
        Dataset.from_list(phase2_data),
        Dataset.from_list(val_phase2)
    )

# ========== ENHANCED TRAINING PHASE ==========
def train_phase(model, train_data, val_data, epochs, lr, phase_name):
    # Use multiple negative ranking loss for better convergence
    loss = losses.MultipleNegativesRankingLoss(model)

    # Create robust evaluator
    evaluator = build_robust_evaluator(val_data)

    # Enhanced training arguments
    training_args = SentenceTransformerTrainingArguments(
        output_dir=os.path.join(SAVE_DIR, phase_name),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE*2,
        num_train_epochs=epochs,
        learning_rate=lr,
        weight_decay=0.01,
        warmup_ratio=0.1,
        eval_strategy="steps",
        logging_strategy="steps",
        eval_steps=100,
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_bambara_eval_cosine_ndcg@10",
        greater_is_better=True,
        logging_dir=os.path.join(SAVE_DIR, "logs"),
        logging_steps=50,
        report_to=[],
        fp16=True
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        loss=loss,
        evaluator=evaluator,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3,
                early_stopping_threshold=MIN_DELTA
            )
        ],
    )

    print(f"\n⭐ Starting {phase_name} training with {len(train_data)} samples")
    trainer.train()

    # Final evaluation
    print("\n📊 Final evaluation results:")
    evaluator(model)

    model.save(os.path.join(SAVE_DIR, f"{phase_name}_final"))
    return model

# ========== MAIN ==========
def main():
    # Load model with better tokenizer handling
    model = SentenceTransformer(MODEL_NAME)

    # Ajout des tokens bambara
    tokenizer = model.tokenizer
    tokenizer.add_tokens(BAMBARA_TOKENS)
    model._first_module().auto_model.resize_token_embeddings(len(tokenizer))
    print(f"Tokenizer enrichi avec {len(BAMBARA_TOKENS)} tokens bambara")

    print("Model loaded with {} parameters".format(sum(p.numel() for p in model.parameters())))

    # Load and split data
    phase1_train, phase1_val, phase2_train, phase2_val = load_and_prepare_data()
    print(f"\nData loaded: {len(phase1_train)} phase1 train, {len(phase1_val)} phase1 val, "
          f"{len(phase2_train)} phase2 train, {len(phase2_val)} phase2 val samples")

    # Phase 1: Monolingual fine-tuning
    print("\n🔵 Phase 1: Monolingual Fine-tuning")
    model = train_phase(
        model, phase1_train, phase1_val,
        EPOCHS_PHASE1, LR_PHASE1, "phase1"
    )

    # Phase 2: Cross-lingual adaptation
    print("\n🟣 Phase 2: Cross-lingual Adaptation")
    model = train_phase(
        model, phase2_train, phase2_val,
        EPOCHS_PHASE2, LR_PHASE2, "phase2"
    )

    # Final save with better metadata
    model.save(os.path.join(SAVE_DIR, "final_model_bambara3"))
    print("\n✅ Training completed successfully!")

    # Test some examples
    test_queries = [
        ("Bonjour comment ça va?", "I ni sogoma, i ka kɛnɛ wa?"),
        ("Quelle est la capitale du Mali?", "Mali faaba ye mun ye?")
    ]
    for q1, q2 in test_queries:
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        sim = util.cos_sim(emb1, emb2).item()
        print(f"Similarity between '{q1}' and '{q2}': {sim:.4f}")

if __name__ == "__main__":
    main()

🚀 Montage de Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/723 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/402 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

Tokenizer enrichi avec 333 tokens bambara
Model loaded with 278299392 parameters

Data loaded: 3217 phase1 train, 860 phase1 val, 3334 phase2 train, 778 phase2 val samples

🔵 Phase 1: Monolingual Fine-tuning

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

⭐ Starting phase1 training with 3217 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.04it/s]

🟣 Phase 2: Cross-lingual Adaptation

⭐ Starting phase2 training with 3334 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.12it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]

✅ Training completed successfully!
Similarity between 'Bonjour comment ça va?' and 'I ni sogoma, i ka kɛnɛ wa?': -0.0300
Similarity between 'Quelle est la capitale du Mali?' and 'Mali faaba ye mun ye?': 0.3531

In [ ]:
import os
import shutil

mount_path = "/content/drive"

# 💥 Supprimer le point de montage si des fichiers y traînent
if os.path.exists(mount_path):
    try:
        shutil.rmtree(mount_path)
        print("Ancien dossier /content/drive supprimé.")
    except Exception as e:
        print(f"Erreur lors de la suppression : {e}")

# ✅ Remontage propre
from google.colab import drive
drive.mount(mount_path, force_remount=True)

Ancien dossier /content/drive supprimé.
Mounted at /content/drive

In [ ]:
import os
import json
import zipfile
import random
from datasets import Dataset
from transformers import EarlyStoppingCallback
from sentence_transformers import SentenceTransformer, losses, util, evaluation
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments
from huggingface_hub import login, HfApi

# ========== CONFIG ==========
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
TRIPLETS_ZIP_PATH = "/content/drive/MyDrive/culture_donnees_sur_drive_sans_variance.zip"
HF_MODEL_NAME = "Fatoumataa/embedding_billingue_francais_bambara"  # Format: username/repo_name
LOCAL_SAVE_DIR = "/content/fine_tuned_model_temp"  # Dossier de sauvegarde temporaire

BATCH_SIZE = 16
EPOCHS_PHASE1 = 10
EPOCHS_PHASE2 = 8
LR_PHASE1 = 2e-5
LR_PHASE2 = 1e-5
MIN_DELTA = 0.0001




# ========== DATA AUGMENTATION ==========
def augment_triplet(triplet):
    """Simple data augmentation for text triplets"""
    augmented = triplet.copy()

    # Random word deletion (10% chance per word)
    for field in ['anchor', 'positive', 'negative']:
        words = triplet[field].split()
        if len(words) > 3 and random.random() < 0.3:
            del_idx = random.randint(0, len(words)-1)
            words.pop(del_idx)
            augmented[field] = ' '.join(words)

    # Synonym replacement (simplified example)
    replacements = {
         # Histoire/Culture
        'griot': ['jeli', 'djéli', 'àkòdànwò'],
        'histoire': ['tariku', 'lisite'],
        'empire': ['mansaya', 'sultani'],
        # Géographie
        'fleuve': ['ba', 'jiba'],
        'capitale': ['faaba', 'duguba'],
        'ville': ['dugu', 'sugo'],
        # Mathématiques
        'calculer': ['sanya', 'kalikuli'],
        'nombre': ['dɔgɔkun', 'nimɔrɔ'],
        'addition': ['fara', 'adision'],
        # Culture générale
        'cérémonie': ['seli', 'ɲɛnajɛ'],
        'tambour': ['dunun', 'tama']
    }

    for field in ['anchor', 'positive', 'negative']:
        for word, syns in replacements.items():
            if word in triplet[field]:
                augmented[field] = augmented[field].replace(word, random.choice(syns))

    return augmented

# ========== ENHANCED EVALUATOR ==========
def build_robust_evaluator(dataset, num_samples=200):
    """Build evaluator with proper train/test split"""
    # Sample evaluation data
    eval_samples = dataset.shuffle().select(range(min(num_samples, len(dataset))))

    queries = {}
    corpus = {}
    relevant_docs = {}

    for idx, sample in enumerate(eval_samples):
        queries[idx] = sample['anchor']
        corpus[2*idx] = sample['positive']
        corpus[2*idx+1] = sample['negative']
        relevant_docs[idx] = [2*idx]  # Only positive is relevant

    return evaluation.InformationRetrievalEvaluator(
        queries, corpus, relevant_docs,
        show_progress_bar=True,
        corpus_chunk_size=512,
        precision_recall_at_k=[3, 5, 10],
        name='bambara_eval'
    )

# ========== IMPROVED DATA LOADING ==========
def load_and_prepare_data():
    with zipfile.ZipFile(TRIPLETS_ZIP_PATH, 'r') as z:
        with z.open(z.namelist()[0]) as f:
            data = json.load(f)

    # Apply simple data augmentation
    augmented_data = []
    for item in data:
        augmented_data.append(item)
        # Add 1 augmented version for each original triplet (50% increase)
        if random.random() < 0.5:
            augmented_data.append(augment_triplet(item))

    # Split into phases with 80/20 train/val split
    random.shuffle(augmented_data)
    split_idx = int(0.8 * len(augmented_data))

    phase1_data, phase2_data = [], []
    for item in augmented_data[:split_idx]:  # Training data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            phase1_data.append(record)
        else:
            phase2_data.append(record)

    # Create validation sets
    val_phase1, val_phase2 = [], []
    for item in augmented_data[split_idx:]:  # Validation data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            val_phase1.append(record)
        else:
            val_phase2.append(record)

    return (
        Dataset.from_list(phase1_data),
        Dataset.from_list(val_phase1),
        Dataset.from_list(phase2_data),
        Dataset.from_list(val_phase2)
    )

# ========== ENHANCED TRAINING PHASE ==========
def train_phase(model, train_data, val_data, epochs, lr, phase_name):
    # Use multiple negative ranking loss for better convergence
    loss = losses.MultipleNegativesRankingLoss(model)

    # Create robust evaluator
    evaluator = build_robust_evaluator(val_data)

    # Enhanced training arguments
    training_args = SentenceTransformerTrainingArguments(
        output_dir=os.path.join(phase_name + "_output"),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE*2,
        num_train_epochs=epochs,
        learning_rate=lr,
        weight_decay=0.01,  # Added regularization
        warmup_ratio=0.1,   # Better learning rate scheduling
        eval_strategy="steps",
        logging_strategy="steps",
        eval_steps=100,
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_bambara_eval_cosine_ndcg@10",
        greater_is_better=True,
        logging_dir=os.path.join("logs"),
        logging_steps=50,
        report_to=[],
        fp16=True  # Enable mixed precision training
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        loss=loss,
        evaluator=evaluator,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3,
                early_stopping_threshold=MIN_DELTA
            )
        ],
    )

    print(f"\n⭐ Starting {phase_name} training with {len(train_data)} samples")
    trainer.train()

    # Final evaluation
    print("\n📊 Final evaluation results:")
    evaluator(model)

    return model





# ========== MAIN ==========
def main():
    # Load model with better tokenizer handling
    model = SentenceTransformer(MODEL_NAME)
    print("Model loaded with {} parameters".format(sum(p.numel() for p in model.parameters())))

    # Load and split data
    phase1_train, phase1_val, phase2_train, phase2_val = load_and_prepare_data()
    print(f"\nData loaded: {len(phase1_train)} phase1 train, {len(phase1_val)} phase1 val, "
          f"{len(phase2_train)} phase2 train, {len(phase2_val)} phase2 val samples")

    # Phase 1: Monolingual fine-tuning
    print("\n🔵 Phase 1: Monolingual Fine-tuning")
    model = train_phase(
        model, phase1_train, phase1_val,
        EPOCHS_PHASE1, LR_PHASE1, "phase1"
    )

    # Phase 2: Cross-lingual adaptation
    print("\n🟣 Phase 2: Cross-lingual Adaptation")
    model = train_phase(
        model, phase2_train, phase2_val,
        EPOCHS_PHASE2, LR_PHASE2, "phase2"
    )

    # ========== NOUVELLE PARTIE ENREGISTREMENT ==========
    print("\n💾 Début de l'enregistrement sur Hugging Face...")
    try:
        # Enregistrement sur Hugging Face Hub
        model.save_to_hub(
            repo_id=HF_MODEL_NAME,
            organization="Fatoumataa",
            commit_message="Modèle final français-bambara",
            private=True
        )
        print(f"\n✅ Modèle enregistré avec succès sur Hugging Face !")
        print(f"🔗 Accès: https://huggingface.co/{HF_MODEL_NAME}")

        # Sauvegarde locale de backup
        model.save(LOCAL_SAVE_DIR)
        print(f"📂 Backup local sauvegardé dans: {LOCAL_SAVE_DIR}")

    except Exception as e:
        print(f"\n❌ Erreur lors de l'enregistrement: {str(e)}")
        print("🔄 Tentative de sauvegarde locale complète...")
        model.save(LOCAL_SAVE_DIR + "_backup")
        print(f"⚠️ Modèle sauvegardé localement dans: {LOCAL_SAVE_DIR}_backup")
        print("Vous pouvez uploader manuellement ce dossier sur Hugging Face Hub")

    # Tests finaux
    test_queries = [
        ("Bonjour comment ça va?", "I ni sogoma, i ka kɛnɛ wa?"),
        ("Quelle est la capitale du Mali?", "Mali faaba ye mun ye?")
    ]
    for q1, q2 in test_queries:
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        sim = util.cos_sim(emb1, emb2).item()
        print(f"Similarity between '{q1}' and '{q2}': {sim:.4f}")

if __name__ == "__main__":
    main()

🚀 Connexion à Hugging Face...
Model loaded with 278043648 parameters

Data loaded: 3265 phase1 train, 811 phase1 val, 3222 phase2 train, 811 phase2 val samples

🔵 Phase 1: Monolingual Fine-tuning

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

⭐ Starting phase1 training with 3265 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.92it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.91it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]

🟣 Phase 2: Cross-lingual Adaptation

⭐ Starting phase2 training with 3222 samples

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.14it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.18it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]
WARNING:sentence_transformers.SentenceTransformer:The `save_to_hub` method is deprecated and will be removed in a future version of SentenceTransformers. Please use `push_to_hub` instead for future model uploads.
WARNING:sentence_transformers.SentenceTransformer:Providing an `organization` to `save_to_hub` is deprecated, please only use `repo_id="Fatoumataa/embedding_billingue_francais_bambara"` instead.

💾 Début de l'enregistrement sur Hugging Face...

❌ Erreur lors de l'enregistrement: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create (Request ID: Root=1-6884f082-0f25c161238fd546721fad5f;0ee54fe4-7e29-4864-a7e2-083ea8cd5833)

You already created this model repo
🔄 Tentative de sauvegarde locale complète...
⚠️ Modèle sauvegardé localement dans: /content/fine_tuned_model_temp_backup
Vous pouvez uploader manuellement ce dossier sur Hugging Face Hub
Similarity between 'Bonjour comment ça va?' and 'I ni sogoma, i ka kɛnɛ wa?': 0.0331
Similarity between 'Quelle est la capitale du Mali?' and 'Mali faaba ye mun ye?': 0.3459

In [ ]:
import os
import json
import zipfile
import random
from datasets import Dataset
from transformers import EarlyStoppingCallback
from sentence_transformers import SentenceTransformer, losses, util, evaluation
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments
from huggingface_hub import login, HfApi
from torch import nn
from google.colab import drive

# Connexion à Hugging Face

# ========== CONFIG ==========
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
TRIPLETS_ZIP_PATH = "/content/drive/MyDrive/culture_donnees_sur_drive_avec_variance.zip"
HF_MODEL_NAME = "Fatoumataa/embedding_billingue_francais_bambara_version_variance"  # Format: username/repo_name
LOCAL_SAVE_DIR = "/content/fine_tuned_model_temp"  # Dossier de sauvegarde temporaire

BATCH_SIZE = 16
EPOCHS_PHASE1_FR = 5  # Phase 1 français
EPOCHS_PHASE1_BM = 5  # Phase 1 bambara
EPOCHS_PHASE2 = 9    # Phase cross-lingue
LR_PHASE1 = 2e-5
LR_PHASE2 = 1e-5
MIN_DELTA = 0.0001
DROPOUT_RATE = 0.15   # Taux de dropout pour éviter le surapprentissage

# Montage Google Drive
print("🚀 Montage de Google Drive...")
drive.mount('/content/drive')


# ========== DATA AUGMENTATION ==========
def augment_triplet(triplet):
    """Simple data augmentation for text triplets"""
    augmented = triplet.copy()

    # Random word deletion (10% chance per word)
    for field in ['anchor', 'positive', 'negative']:
        words = triplet[field].split()
        if len(words) > 3 and random.random() < 0.3:
            del_idx = random.randint(0, len(words)-1)
            words.pop(del_idx)
            augmented[field] = ' '.join(words)

    # Synonym replacement (simplified example)
    replacements = {
         # Histoire/Culture
        'griot': ['jeli', 'djéli', 'àkòdànwò'],
        'histoire': ['tariku', 'lisite'],
        'empire': ['mansaya', 'sultani'],
        # Géographie
        'fleuve': ['ba', 'jiba'],
        'capitale': ['faaba', 'duguba'],
        'ville': ['dugu', 'sugo'],
        # Mathématiques
        'calculer': ['sanya', 'kalikuli'],
        'nombre': ['dɔgɔkun', 'nimɔrɔ'],
        'addition': ['fara', 'adision'],
        # Culture générale
        'cérémonie': ['seli', 'ɲɛnajɛ'],
        'tambour': ['dunun', 'tama']
    }

    for field in ['anchor', 'positive', 'negative']:
        for word, syns in replacements.items():
            if word in triplet[field]:
                augmented[field] = augmented[field].replace(word, random.choice(syns))

    return augmented

# ========== ENHANCED EVALUATOR ==========
def build_robust_evaluator(dataset, num_samples=200):
    """Build evaluator with proper train/test split"""
    # Sample evaluation data
    eval_samples = dataset.shuffle().select(range(min(num_samples, len(dataset))))

    queries = {}
    corpus = {}
    relevant_docs = {}

    for idx, sample in enumerate(eval_samples):
        queries[idx] = sample['anchor']
        corpus[2*idx] = sample['positive']
        corpus[2*idx+1] = sample['negative']
        relevant_docs[idx] = [2*idx]  # Only positive is relevant

    return evaluation.InformationRetrievalEvaluator(
        queries, corpus, relevant_docs,
        show_progress_bar=True,
        corpus_chunk_size=512,
        precision_recall_at_k=[3, 5, 10],
        name='bambara_eval'
    )

# ========== IMPROVED DATA LOADING ==========
def load_and_prepare_data():
    with zipfile.ZipFile(TRIPLETS_ZIP_PATH, 'r') as z:
        with z.open(z.namelist()[0]) as f:
            data = json.load(f)

    # Apply simple data augmentation
    augmented_data = []
    for item in data:
        augmented_data.append(item)
        # Add 1 augmented version for each original triplet (50% increase)
        if random.random() < 0.5:
            augmented_data.append(augment_triplet(item))

    # Split into phases with 80/20 train/val split
    random.shuffle(augmented_data)
    split_idx = int(0.8 * len(augmented_data))

    phase1_fr_data, phase1_bm_data, phase2_data = [], [], []
    for item in augmented_data[:split_idx]:  # Training data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            if item["langue"] == "français":
                phase1_fr_data.append(record)
            else:  # bambara
                phase1_bm_data.append(record)
        else:
            phase2_data.append(record)

    # Create validation sets
    val_phase1_fr, val_phase1_bm, val_phase2 = [], [], []
    for item in augmented_data[split_idx:]:  # Validation data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            if item["langue"] == "français":
                val_phase1_fr.append(record)
            else:  # bambara
                val_phase1_bm.append(record)
        else:
            val_phase2.append(record)

    return (
        Dataset.from_list(phase1_fr_data),
        Dataset.from_list(phase1_bm_data),
        Dataset.from_list(val_phase1_fr),
        Dataset.from_list(val_phase1_bm),
        Dataset.from_list(phase2_data),
        Dataset.from_list(val_phase2)
    )

# ========== ENHANCED TRAINING PHASE ==========
def train_phase(model, train_data, val_data, epochs, lr, phase_name):
    # Use multiple negative ranking loss for better convergence
    loss = losses.MultipleNegativesRankingLoss(model)

    # Create robust evaluator
    evaluator = build_robust_evaluator(val_data)

    # Enhanced training arguments
    training_args = SentenceTransformerTrainingArguments(
        output_dir=os.path.join(phase_name + "_output"),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE*2,
        num_train_epochs=epochs,
        learning_rate=lr,
        weight_decay=0.01,  # Added regularization
        warmup_ratio=0.1,   # Better learning rate scheduling
        eval_strategy="steps",
        logging_strategy="steps",
        eval_steps=100,
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_bambara_eval_cosine_ndcg@10",
        greater_is_better=True,
        logging_dir=os.path.join("logs"),
        logging_steps=50,
        report_to=[],
        fp16=True  # Enable mixed precision training
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        loss=loss,
        evaluator=evaluator,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3,
                early_stopping_threshold=MIN_DELTA
            )
        ],
    )

    print(f"\n⭐ Starting {phase_name} training with {len(train_data)} samples")
    trainer.train()

    # Final evaluation
    print("\n📊 Final evaluation results:")
    evaluator(model)

    return model

# ========== MAIN ==========
def main():
    # Load model with better tokenizer handling
    model = SentenceTransformer(MODEL_NAME)

    # Ajout du dropout pour éviter le surapprentissage

    # Récupérer le modèle de base
    base_model = model._first_module().auto_model


# Appliquer le dropout à la couche de pooler si elle existe

    if hasattr(base_model, 'pooler') and hasattr(base_model.pooler, 'dense'):
      base_model.pooler.dense = nn.Sequential(
      nn.Dropout(DROPOUT_RATE),
      base_model.pooler.dense
    )



    print("Model loaded with {} parameters".format(sum(p.numel() for p in model.parameters())))

    # Load and split data
    phase1_fr_train, phase1_bm_train, phase1_fr_val, phase1_bm_val, phase2_train, phase2_val = load_and_prepare_data()
    print(f"\nData loaded: {len(phase1_fr_train)} phase1_fr train, {len(phase1_bm_train)} phase1_bm train, "
          f"{len(phase1_fr_val)} phase1_fr val, {len(phase1_bm_val)} phase1_bm val, "
          f"{len(phase2_train)} phase2 train, {len(phase2_val)} phase2 val samples")

    # Phase 1a: Monolingual fine-tuning français
    print("\n🔵 Phase 1a: Monolingual Fine-tuning (Français)")
    model = train_phase(
        model, phase1_fr_train, phase1_fr_val,
        EPOCHS_PHASE1_FR, LR_PHASE1, "phase1_fr"
    )

    # Phase 1b: Monolingual fine-tuning bambara
    print("\n🔵 Phase 1b: Monolingual Fine-tuning (Bambara)")
    model = train_phase(
        model, phase1_bm_train, phase1_bm_val,
        EPOCHS_PHASE1_BM, LR_PHASE1, "phase1_bm"
    )

    # Phase 2: Cross-lingual adaptation
    print("\n🟣 Phase 2: Cross-lingual Adaptation")
    model = train_phase(
        model, phase2_train, phase2_val,
        EPOCHS_PHASE2, LR_PHASE2, "phase2"
    )

    # ========== NOUVELLE PARTIE ENREGISTREMENT ==========
    print("\n💾 Début de l'enregistrement sur Hugging Face...")
    try:
        # Enregistrement sur Hugging Face Hub
        model.save_to_hub(
            repo_id=HF_MODEL_NAME,
            organization="Fatoumataa",
            commit_message="Modèle final français-bambara",
            private=True
        )
        print(f"\n✅ Modèle enregistré avec succès sur Hugging Face !")
        print(f"🔗 Accès: https://huggingface.co/{HF_MODEL_NAME}")

        # Sauvegarde locale de backup
        model.save(LOCAL_SAVE_DIR)
        print(f"📂 Backup local sauvegardé dans: {LOCAL_SAVE_DIR}")

    except Exception as e:
        print(f"\n❌ Erreur lors de l'enregistrement: {str(e)}")
        print("🔄 Tentative de sauvegarde locale complète...")
        model.save(LOCAL_SAVE_DIR + "_backup")
        print(f"⚠️ Modèle sauvegardé localement dans: {LOCAL_SAVE_DIR}_backup")
        print("Vous pouvez uploader manuellement ce dossier sur Hugging Face Hub")

    # Tests finaux
    test_queries = [
        ("Bonjour comment ça va?", "I ni sogoma, i ka kɛnɛ wa?"),
        ("Quelle est la capitale du Mali?", "Mali faaba ye mun ye?")
    ]
    for q1, q2 in test_queries:
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        sim = util.cos_sim(emb1, emb2).item()
        print(f"Similarity between '{q1}' and '{q2}': {sim:.4f}")

if __name__ == "__main__":
    main()

🚀 Connexion à Hugging Face...
🚀 Montage de Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Model loaded with 278043648 parameters

Data loaded: 3019 phase1_fr train, 2947 phase1_bm train, 730 phase1_fr val, 780 phase1_bm val, 6019 phase2 train, 1487 phase2 val samples

🔵 Phase 1a: Monolingual Fine-tuning (Français)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

⭐ Starting phase1_fr training with 3019 samples

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.60it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.75it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.63it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.54it/s]

🔵 Phase 1b: Monolingual Fine-tuning (Bambara)

⭐ Starting phase1_bm training with 2947 samples

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]

🟣 Phase 2: Cross-lingual Adaptation

⭐ Starting phase2 training with 6019 samples

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.98it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s]

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
WARNING:sentence_transformers.SentenceTransformer:The `save_to_hub` method is deprecated and will be removed in a future version of SentenceTransformers. Please use `push_to_hub` instead for future model uploads.
WARNING:sentence_transformers.SentenceTransformer:Providing an `organization` to `save_to_hub` is deprecated, please only use `repo_id="Fatoumataa/embedding_billingue_francais_bambara_version_variance"` instead.

💾 Début de l'enregistrement sur Hugging Face...

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Upload 3 LFS files:   0%|          | 0/3 [00:00<?, ?it/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

✅ Modèle enregistré avec succès sur Hugging Face !
🔗 Accès: https://huggingface.co/Fatoumataa/embedding_billingue_francais_bambara_version_variance
📂 Backup local sauvegardé dans: /content/fine_tuned_model_temp
Similarity between 'Bonjour comment ça va?' and 'I ni sogoma, i ka kɛnɛ wa?': 0.0817
Similarity between 'Quelle est la capitale du Mali?' and 'Mali faaba ye mun ye?': 0.5076

In [ ]:
#le test ici
from sentence_transformers import SentenceTransformer, util
import json

import numpy as np


# Charger votre modèle
model = SentenceTransformer("Fatoumataa/embedding_billingue_francais_bambara_version_variance")

# Liste de tests : (question, bonne_reponse, mauvaise_reponse, langue)
test_cases = [
      # 1. Test de base (identique à l'entraînement)
    (
        "quel est cet instrument malien, symbole des contes et des récits, souvent associé aux griots ?",
        "la kora. cet instrument à cordes est central dans la musique des griots",
        "le balafon est un xylophone traditionnel ouest-africain",
        "fr"
    ),

    # 2. Variante lexicale
    (
        "nommez l'instrument des griots pour accompagner les épopées historiques",
        "la kora, harpe-luth mandingue à 21 cordes",
        "le djembé, tambour en gobelet pour les rythmes",
        "fr"
    ),

    # 3. Négatif plausible
    (
        "quel objet utilisent les griots pour chanter les généalogies ?",
        "la kora aux cordes en boyau",
        "le n'goni, luth à 4 cordes pour les chants de chasse",
        "fr"
    )
    ,
    # 4. Test direct
    (
        "Mali fɔlifɛn jumɛn bɛ wele tuma caman na ko ' harpe-luth ' ?",
        "kora ye. nin fɔlifɛn min bɛ fɔ ni juru ye",
        "balafon (balafon) ye farafinna xylophone ye",
        "bm"
    ),

    # 5. Variante syntaxique
    (
        "jeliw bɛ fɔlifɛn jumɛn fɛ ka maanaw kɛ ?",
        "kora ye fɔlifɛn ye min ka di jeliw fɛ",
        "tama ye fɔlifɛn ye min bɛ kɛ ni gbolo ye",
        "bm"
    ),

    # 6. Négatif culturellement proche
    (
        "fɔlifɛn jumɛn bɛ kɛ ka tariku sɛbɛn ?",
        "kora bɛ kɛ ka maanaw sɛbɛn ni dɔnkili ye",
        "dununba bɛ kɛ ka fɔli dɔn nka a tɛ sɛbɛn",
        "bm"
    ),
      # 7. Français → Bambara (identique à l'entraînement)
    (
        "quel est le rôle principal des griots dans la société malienne traditionnelle ?",
        "griotw ye daɲɛw laada kɔlɔsibagaw ye",
        "Ni aw ye a ɲimi ka ɲɛ, o bɛ dumuni toli nɔgɔya",
        "fr→bm"
    ),

    # 8. Bambara → Français (identique à l'entraînement)
    (
        "jeliw nafa ka bon cogo di ?",
        "les griots sont les gardiens de la tradition orale",
        "Les forgerons travaillent le métal traditionnel",
        "bm→fr"
    ),
     # 9. Reformulation de l'ancre (Français)
    (
        "citez l'instrument emblématique des conteurs maliens",
        "la kora sert à accompagner les récits historiques",
        "le bolon est une harpe arquée pour les cérémonies",
        "fr"
    ),

    # 10. Négatif technique (Bambara)
    (
        "fɔlifɛn jumɛn bɛ kɛ ni juru ye ?",
        "kora bɛ kɛ ni juru 21 ye",
        "n'goni bɛ kɛ ni juru 4 ye",
        "bm"
    ),

    # 11. Question piège (Cross-lingual)
    (
        "quelle est la fonction sociale des griots ?",
        "u bɛ tariku laseli ani dɔnkiliw fɛ",
        "u bɛ farikolo kɛ ni sɛnɛ fɛ",
        "fr→bm"
    ),

    # 12. Validation de compréhension (Bambara→Français)
    (
        "kuma fɔcogo ɲuman bɛ kɛ sababu ye ?",
        "une bonne articulation permet une compréhension claire",
        "parler fort aide à être entendu de loin",
        "bm→fr"
    )
]

def evaluate_model(test_cases, model, similarity_threshold=0.5):
    results = []
    for i, (query, pos, neg, lang) in enumerate(test_cases):
        # Encodage
        query_emb = model.encode(query)
        pos_emb = model.encode(pos)
        neg_emb = model.encode(neg)

        # Calcul des similarités
        pos_sim = util.cos_sim(query_emb, pos_emb).item()
        neg_sim = util.cos_sim(query_emb, neg_emb).item()

        # Évaluation
        correct_pos = pos_sim >= similarity_threshold
        correct_neg = neg_sim < similarity_threshold
        passed = correct_pos and correct_neg

        results.append({
            "id": i+1,
            "lang": lang,
            "query": query,
            "pos": pos,
            "neg": neg,
            "pos_sim": pos_sim,
            "neg_sim": neg_sim,
            "passed": passed
        })

    return results

# Exécution du test
results = evaluate_model(test_cases, model)

# Affichage des résultats
print("🔍 Résultats des tests 🔍\n")
for r in results:
    print(f"Test #{r['id']} ({r['lang']}): {'✅' if r['passed'] else '❌'}")
    print(f"Question: {r['query']}")
    print(f"  [+] {r['pos'][:60]}... (similarité: {r['pos_sim']:.4f})")
    print(f"  [-] {r['neg'][:60]}... (similarité: {r['neg_sim']:.4f})")
    print("-"*80)

# Stats globales
passed = sum(1 for r in results if r['passed'])
print(f"\n📊 Score: {passed}/{len(results)} ({passed/len(results)*100:.1f}%)")
print("Seuil de similarité recommandé : 0.4-0.7 pour les bonnes paires")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/32.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/697 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Some weights of the model checkpoint at Fatoumataa/embedding_billingue_francais_bambara_version_variance were not used when initializing XLMRobertaModel: ['pooler.dense.1.bias', 'pooler.dense.1.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLMRobertaModel were not initialized from the model checkpoint at Fatoumataa/embedding_billingue_francais_bambara_version_variance and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

🔍 Résultats des tests 🔍

Test #1 (fr): ✅
Question: quel est cet instrument malien, symbole des contes et des récits, souvent associé aux griots ?
  [+] la kora. cet instrument à cordes est central dans la musique... (similarité: 0.7527)
  [-] le balafon est un xylophone traditionnel ouest-africain... (similarité: 0.2272)
--------------------------------------------------------------------------------
Test #2 (fr): ❌
Question: nommez l'instrument des griots pour accompagner les épopées historiques
  [+] la kora, harpe-luth mandingue à 21 cordes... (similarité: 0.3457)
  [-] le djembé, tambour en gobelet pour les rythmes... (similarité: 0.3124)
--------------------------------------------------------------------------------
Test #3 (fr): ❌
Question: quel objet utilisent les griots pour chanter les généalogies ?
  [+] la kora aux cordes en boyau... (similarité: 0.2097)
  [-] le n'goni, luth à 4 cordes pour les chants de chasse... (similarité: 0.2358)
--------------------------------------------------------------------------------
Test #4 (bm): ✅
Question: Mali fɔlifɛn jumɛn bɛ wele tuma caman na ko ' harpe-luth ' ?
  [+] kora ye. nin fɔlifɛn min bɛ fɔ ni juru ye... (similarité: 0.5896)
  [-] balafon (balafon) ye farafinna xylophone ye... (similarité: 0.1427)
--------------------------------------------------------------------------------
Test #5 (bm): ❌
Question: jeliw bɛ fɔlifɛn jumɛn fɛ ka maanaw kɛ ?
  [+] kora ye fɔlifɛn ye min ka di jeliw fɛ... (similarité: 0.4356)
  [-] tama ye fɔlifɛn ye min bɛ kɛ ni gbolo ye... (similarité: 0.2975)
--------------------------------------------------------------------------------
Test #6 (bm): ❌
Question: fɔlifɛn jumɛn bɛ kɛ ka tariku sɛbɛn ?
  [+] kora bɛ kɛ ka maanaw sɛbɛn ni dɔnkili ye... (similarité: 0.2394)
  [-] dununba bɛ kɛ ka fɔli dɔn nka a tɛ sɛbɛn... (similarité: 0.3360)
--------------------------------------------------------------------------------
Test #7 (fr→bm): ✅
Question: quel est le rôle principal des griots dans la société malienne traditionnelle ?
  [+] griotw ye daɲɛw laada kɔlɔsibagaw ye... (similarité: 0.7652)
  [-] Ni aw ye a ɲimi ka ɲɛ, o bɛ dumuni toli nɔgɔya... (similarité: -0.1207)
--------------------------------------------------------------------------------
Test #8 (bm→fr): ❌
Question: jeliw nafa ka bon cogo di ?
  [+] les griots sont les gardiens de la tradition orale... (similarité: 0.5000)
  [-] Les forgerons travaillent le métal traditionnel... (similarité: 0.1206)
--------------------------------------------------------------------------------
Test #9 (fr): ❌
Question: citez l'instrument emblématique des conteurs maliens
  [+] la kora sert à accompagner les récits historiques... (similarité: -0.0615)
  [-] le bolon est une harpe arquée pour les cérémonies... (similarité: -0.0041)
--------------------------------------------------------------------------------
Test #10 (bm): ❌
Question: fɔlifɛn jumɛn bɛ kɛ ni juru ye ?
  [+] kora bɛ kɛ ni juru 21 ye... (similarité: 0.5965)
  [-] n'goni bɛ kɛ ni juru 4 ye... (similarité: 0.5872)
--------------------------------------------------------------------------------
Test #11 (fr→bm): ❌
Question: quelle est la fonction sociale des griots ?
  [+] u bɛ tariku laseli ani dɔnkiliw fɛ... (similarité: 0.0582)
  [-] u bɛ farikolo kɛ ni sɛnɛ fɛ... (similarité: -0.0292)
--------------------------------------------------------------------------------
Test #12 (bm→fr): ✅
Question: kuma fɔcogo ɲuman bɛ kɛ sababu ye ?
  [+] une bonne articulation permet une compréhension claire... (similarité: 0.5228)
  [-] parler fort aide à être entendu de loin... (similarité: 0.4111)
--------------------------------------------------------------------------------

📊 Score: 4/12 (33.3%)
Seuil de similarité recommandé : 0.4-0.7 pour les bonnes paires

In [ ]:
# 
import os
import json
import zipfile
import random
from datasets import Dataset
from transformers import EarlyStoppingCallback
from sentence_transformers import SentenceTransformer, losses, util, evaluation
from sentence_transformers.trainer import SentenceTransformerTrainer
from sentence_transformers.training_args import SentenceTransformerTrainingArguments
from huggingface_hub import login, HfApi
# from google.colab import drive


 

# Charger votre modèle
MODEL_NAME = "Fatoumataa/embedding_billingue_francais_bambara"
TRIPLETS_ZIP_PATH = "/content/drive/MyDrive/fichier2_sans_doublons.zip"
HF_MODEL_NAME = "Fatoumataa/embedding_billingue_francais_bambara_version3"  
LOCAL_SAVE_DIR = "/content/fine_tuned_model_temp"  # Dossier de sauvegarde temporaire

BATCH_SIZE = 16
EPOCHS_PHASE1 = 6
EPOCHS_PHASE2 = 6
LR_PHASE1 = 2e-5
LR_PHASE2 = 1e-5
MIN_DELTA = 0.0001

# ========== DATA AUGMENTATION ==========
def augment_triplet(triplet):
    """Simple data augmentation for text triplets"""
    augmented = triplet.copy()

    # Random word deletion (10% chance per word)
    for field in ['anchor', 'positive', 'negative']:
        words = triplet[field].split()
        if len(words) > 3 and random.random() < 0.3:
            del_idx = random.randint(0, len(words)-1)
            words.pop(del_idx)
            augmented[field] = ' '.join(words)

    # Synonym replacement (simplified example)
    replacements = {
         # Histoire/Culture
        'griot': ['jeli', 'djéli', 'àkòdànwò'],
        'histoire': ['tariku', 'lisite'],
        'empire': ['mansaya', 'sultani'],
        # Géographie
        'fleuve': ['ba', 'jiba'],
        'capitale': ['faaba', 'duguba'],
        'ville': ['dugu', 'sugo'],
        # Mathématiques
        'calculer': ['sanya', 'kalikuli'],
        'nombre': ['dɔgɔkun', 'nimɔrɔ'],
        'addition': ['fara', 'adision'],
        # Culture générale
        'cérémonie': ['seli', 'ɲɛnajɛ'],
        'tambour': ['dunun', 'tama']
    }

    for field in ['anchor', 'positive', 'negative']:
        for word, syns in replacements.items():
            if word in triplet[field]:
                augmented[field] = augmented[field].replace(word, random.choice(syns))

    return augmented

# ========== ENHANCED EVALUATOR ==========
def build_robust_evaluator(dataset, num_samples=200):
    """Build evaluator with proper train/test split"""
    # Sample evaluation data
    eval_samples = dataset.shuffle().select(range(min(num_samples, len(dataset))))

    queries = {}
    corpus = {}
    relevant_docs = {}

    for idx, sample in enumerate(eval_samples):
        queries[idx] = sample['anchor']
        corpus[2*idx] = sample['positive']
        corpus[2*idx+1] = sample['negative']
        relevant_docs[idx] = [2*idx]  # Only positive is relevant

    return evaluation.InformationRetrievalEvaluator(
        queries, corpus, relevant_docs,
        show_progress_bar=True,
        corpus_chunk_size=512,
        precision_recall_at_k=[3, 5, 10],
        name='bambara_eval'
    )

# ========== IMPROVED DATA LOADING ==========
def load_and_prepare_data():
    with zipfile.ZipFile(TRIPLETS_ZIP_PATH, 'r') as z:
        with z.open(z.namelist()[0]) as f:
            data = json.load(f)

    # Apply simple data augmentation
    augmented_data = []
    for item in data:
        augmented_data.append(item)
        # Add 1 augmented version for each original triplet (50% increase)
        if random.random() < 0.5:
            augmented_data.append(augment_triplet(item))

    # Split into phases with 80/20 train/val split
    random.shuffle(augmented_data)
    split_idx = int(0.8 * len(augmented_data))

    phase1_data, phase2_data = [], []
    for item in augmented_data[:split_idx]:  # Training data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            phase1_data.append(record)
        else:
            phase2_data.append(record)

    # Create validation sets
    val_phase1, val_phase2 = [], []
    for item in augmented_data[split_idx:]:  # Validation data
        record = {
            "anchor": item["anchor"],
            "positive": item["positive"],
            "negative": item["negative"],
            "label": 1.0
        }
        if item["langue"] == item.get("positive_langue", item["langue"]):
            val_phase1.append(record)
        else:
            val_phase2.append(record)

    return (
        Dataset.from_list(phase1_data),
        Dataset.from_list(val_phase1),
        Dataset.from_list(phase2_data),
        Dataset.from_list(val_phase2)
    )

# ========== ENHANCED TRAINING PHASE ==========
def train_phase(model, train_data, val_data, epochs, lr, phase_name):
    # Use multiple negative ranking loss for better convergence
    loss = losses.MultipleNegativesRankingLoss(model)

    # Create robust evaluator
    evaluator = build_robust_evaluator(val_data)

    # Enhanced training arguments
    training_args = SentenceTransformerTrainingArguments(
        output_dir=os.path.join(phase_name + "_output"),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE*2,
        num_train_epochs=epochs,
        learning_rate=lr,
        weight_decay=0.01,  # Added regularization
        warmup_ratio=0.1,   # Better learning rate scheduling
        eval_strategy="steps",
        logging_strategy="steps",
        eval_steps=100,
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_bambara_eval_cosine_ndcg@10",
        greater_is_better=True,
        logging_dir=os.path.join("logs"),
        logging_steps=50,
        report_to=[],
        fp16=True  # Enable mixed precision training
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        loss=loss,
        evaluator=evaluator,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3,
                early_stopping_threshold=MIN_DELTA
            )
        ],
    )

    print(f"\n⭐ Starting {phase_name} training with {len(train_data)} samples")
    trainer.train()

    # Final evaluation
    print("\n📊 Final evaluation results:")
    evaluator(model)

    return model





# ========== MAIN ==========
def main():
    # Load model with better tokenizer handling
    model = SentenceTransformer(MODEL_NAME)
    print("Model loaded with {} parameters".format(sum(p.numel() for p in model.parameters())))

    # Load and split data
    phase1_train, phase1_val, phase2_train, phase2_val = load_and_prepare_data()
    print(f"\nData loaded: {len(phase1_train)} phase1 train, {len(phase1_val)} phase1 val, "
          f"{len(phase2_train)} phase2 train, {len(phase2_val)} phase2 val samples")

    # Phase 1: Monolingual fine-tuning
    print("\n🔵 Phase 1: Monolingual Fine-tuning")
    model = train_phase(
        model, phase1_train, phase1_val,
        EPOCHS_PHASE1, LR_PHASE1, "phase1"
    )

    # Phase 2: Cross-lingual adaptation
    print("\n🟣 Phase 2: Cross-lingual Adaptation")
    model = train_phase(
        model, phase2_train, phase2_val,
        EPOCHS_PHASE2, LR_PHASE2, "phase2"
    )

    # ========== NOUVELLE PARTIE ENREGISTREMENT ==========
    print("\n💾 Début de l'enregistrement sur Hugging Face...")
    try:
        # Enregistrement sur Hugging Face Hub
        model.save_to_hub(
            repo_id=HF_MODEL_NAME,
            organization="Fatoumataa",
            commit_message="Modèle final français-bambara",
            private=True
        )
        print(f"\n✅ Modèle enregistré avec succès sur Hugging Face !")
        print(f"🔗 Accès: https://huggingface.co/{HF_MODEL_NAME}")

        # Sauvegarde locale de backup
        model.save(LOCAL_SAVE_DIR)
        print(f"📂 Backup local sauvegardé dans: {LOCAL_SAVE_DIR}")

    except Exception as e:
        print(f"\n❌ Erreur lors de l'enregistrement: {str(e)}")
        print("🔄 Tentative de sauvegarde locale complète...")
        model.save(LOCAL_SAVE_DIR + "_backup")
        print(f"⚠️ Modèle sauvegardé localement dans: {LOCAL_SAVE_DIR}_backup")
        print("Vous pouvez uploader manuellement ce dossier sur Hugging Face Hub")

    # Tests finaux
    test_queries = [
        ("Bonjour comment ça va?", "I ni sogoma, i ka kɛnɛ wa?"),
        ("Quelle est la capitale du Mali?", "Mali faaba ye mun ye?")
    ]
    for q1, q2 in test_queries:
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        sim = util.cos_sim(emb1, emb2).item()
        print(f"Similarity between '{q1}' and '{q2}': {sim:.4f}")

if __name__ == "__main__":
    main()

Model loaded with 278043648 parameters

Data loaded: 1082 phase1 train, 293 phase1 val, 1125 phase2 train, 259 phase2 val samples

🔵 Phase 1: Monolingual Fine-tuning

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

⭐ Starting phase1 training with 1082 samples

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.31it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.25it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.19it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

🟣 Phase 2: Cross-lingual Adaptation

⭐ Starting phase2 training with 1125 samples

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.21it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.13it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

📊 Final evaluation results:

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/13 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [00:00<00:00,  2.21it/s]
WARNING:sentence_transformers.SentenceTransformer:The `save_to_hub` method is deprecated and will be removed in a future version of SentenceTransformers. Please use `push_to_hub` instead for future model uploads.
WARNING:sentence_transformers.SentenceTransformer:Providing an `organization` to `save_to_hub` is deprecated, please only use `repo_id="Fatoumataa/embedding_billingue_francais_bambara_version3"` instead.

💾 Début de l'enregistrement sur Hugging Face...

Upload 3 LFS files:   0%|          | 0/3 [00:00<?, ?it/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

✅ Modèle enregistré avec succès sur Hugging Face !
🔗 Accès: https://huggingface.co/Fatoumataa/embedding_billingue_francais_bambara_version3
📂 Backup local sauvegardé dans: /content/fine_tuned_model_temp
Similarity between 'Bonjour comment ça va?' and 'I ni sogoma, i ka kɛnɛ wa?': -0.0147
Similarity between 'Quelle est la capitale du Mali?' and 'Mali faaba ye mun ye?': 0.4989

In [ ]:
#le test ici
from sentence_transformers import SentenceTransformer, util
import json

import numpy as np


# Charger votre modèle
model = SentenceTransformer("Fatoumataa/embedding_billingue_francais_bambara_version3")

# Liste de tests : (question, bonne_reponse, mauvaise_reponse, langue)
test_cases = [
      # 1. Test de base (identique à l'entraînement)
    (
        "quel est cet instrument malien, symbole des contes et des récits, souvent associé aux griots ?",
        "la kora. cet instrument à cordes est central dans la musique des griots",
        "le balafon est un xylophone traditionnel ouest-africain",
        "fr"
    ),

    # 2. Variante lexicale
    (
        "nommez l'instrument des griots pour accompagner les épopées historiques",
        "la kora, harpe-luth mandingue à 21 cordes",
        "le djembé, tambour en gobelet pour les rythmes",
        "fr"
    ),

    # 3. Négatif plausible
    (
        "quel objet utilisent les griots pour chanter les généalogies ?",
        "la kora aux cordes en boyau",
        "le n'goni, luth à 4 cordes pour les chants de chasse",
        "fr"
    )
    ,
    # 4. Test direct
    (
        "Mali fɔlifɛn jumɛn bɛ wele tuma caman na ko ' harpe-luth ' ?",
        "kora ye. nin fɔlifɛn min bɛ fɔ ni juru ye",
        "balafon (balafon) ye farafinna xylophone ye",
        "bm"
    ),

    # 5. Variante syntaxique
    (
        "jeliw bɛ fɔlifɛn jumɛn fɛ ka maanaw kɛ ?",
        "kora ye fɔlifɛn ye min ka di jeliw fɛ",
        "tama ye fɔlifɛn ye min bɛ kɛ ni gbolo ye",
        "bm"
    ),

    # 6. Négatif culturellement proche
    (
        "fɔlifɛn jumɛn bɛ kɛ ka tariku sɛbɛn ?",
        "kora bɛ kɛ ka maanaw sɛbɛn ni dɔnkili ye",
        "dununba bɛ kɛ ka fɔli dɔn nka a tɛ sɛbɛn",
        "bm"
    ),
      # 7. Français → Bambara (identique à l'entraînement)
    (
        "quel est le rôle principal des griots dans la société malienne traditionnelle ?",
        "griotw ye daɲɛw laada kɔlɔsibagaw ye",
        "Ni aw ye a ɲimi ka ɲɛ, o bɛ dumuni toli nɔgɔya",
        "fr→bm"
    ),

    # 8. Bambara → Français (identique à l'entraînement)
    (
        "jeliw nafa ka bon cogo di ?",
        "les griots sont les gardiens de la tradition orale",
        "Les forgerons travaillent le métal traditionnel",
        "bm→fr"
    ),
     # 9. Reformulation de l'ancre (Français)
    (
        "citez l'instrument emblématique des conteurs maliens",
        "la kora sert à accompagner les récits historiques",
        "le bolon est une harpe arquée pour les cérémonies",
        "fr"
    ),

    # 10. Négatif technique (Bambara)
    (
        "fɔlifɛn jumɛn bɛ kɛ ni juru ye ?",
        "kora bɛ kɛ ni juru 21 ye",
        "n'goni bɛ kɛ ni juru 4 ye",
        "bm"
    ),

    # 11. Question piège (Cross-lingual)
    (
        "quelle est la fonction sociale des griots ?",
        "u bɛ tariku laseli ani dɔnkiliw fɛ",
        "u bɛ farikolo kɛ ni sɛnɛ fɛ",
        "fr→bm"
    ),

    # 12. Validation de compréhension (Bambara→Français)
    (
        "kuma fɔcogo ɲuman bɛ kɛ sababu ye ?",
        "une bonne articulation permet une compréhension claire",
        "parler fort aide à être entendu de loin",
        "bm→fr"
    )
]

def evaluate_model(test_cases, model, similarity_threshold=0.5):
    results = []
    for i, (query, pos, neg, lang) in enumerate(test_cases):
        # Encodage
        query_emb = model.encode(query)
        pos_emb = model.encode(pos)
        neg_emb = model.encode(neg)

        # Calcul des similarités
        pos_sim = util.cos_sim(query_emb, pos_emb).item()
        neg_sim = util.cos_sim(query_emb, neg_emb).item()

        # Évaluation
        correct_pos = pos_sim >= similarity_threshold
        correct_neg = neg_sim < similarity_threshold
        passed = correct_pos and correct_neg

        results.append({
            "id": i+1,
            "lang": lang,
            "query": query,
            "pos": pos,
            "neg": neg,
            "pos_sim": pos_sim,
            "neg_sim": neg_sim,
            "passed": passed
        })

    return results

# Exécution du test
results = evaluate_model(test_cases, model)

# Affichage des résultats
print("🔍 Résultats des tests 🔍\n")
for r in results:
    print(f"Test #{r['id']} ({r['lang']}): {'✅' if r['passed'] else '❌'}")
    print(f"Question: {r['query']}")
    print(f"  [+] {r['pos'][:60]}... (similarité: {r['pos_sim']:.4f})")
    print(f"  [-] {r['neg'][:60]}... (similarité: {r['neg_sim']:.4f})")
    print("-"*80)

# Stats globales
passed = sum(1 for r in results if r['passed'])
print(f"\n📊 Score: {passed}/{len(results)} ({passed/len(results)*100:.1f}%)")
print("Seuil de similarité recommandé : 0.4-0.7 pour les bonnes paires")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/27.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/697 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

🔍 Résultats des tests 🔍

Test #1 (fr): ✅
Question: quel est cet instrument malien, symbole des contes et des récits, souvent associé aux griots ?
  [+] la kora. cet instrument à cordes est central dans la musique... (similarité: 0.7119)
  [-] le balafon est un xylophone traditionnel ouest-africain... (similarité: 0.3845)
--------------------------------------------------------------------------------
Test #2 (fr): ❌
Question: nommez l'instrument des griots pour accompagner les épopées historiques
  [+] la kora, harpe-luth mandingue à 21 cordes... (similarité: 0.3468)
  [-] le djembé, tambour en gobelet pour les rythmes... (similarité: 0.3281)
--------------------------------------------------------------------------------
Test #3 (fr): ❌
Question: quel objet utilisent les griots pour chanter les généalogies ?
  [+] la kora aux cordes en boyau... (similarité: 0.3680)
  [-] le n'goni, luth à 4 cordes pour les chants de chasse... (similarité: 0.3184)
--------------------------------------------------------------------------------
Test #4 (bm): ✅
Question: Mali fɔlifɛn jumɛn bɛ wele tuma caman na ko ' harpe-luth ' ?
  [+] kora ye. nin fɔlifɛn min bɛ fɔ ni juru ye... (similarité: 0.6896)
  [-] balafon (balafon) ye farafinna xylophone ye... (similarité: 0.3529)
--------------------------------------------------------------------------------
Test #5 (bm): ✅
Question: jeliw bɛ fɔlifɛn jumɛn fɛ ka maanaw kɛ ?
  [+] kora ye fɔlifɛn ye min ka di jeliw fɛ... (similarité: 0.6301)
  [-] tama ye fɔlifɛn ye min bɛ kɛ ni gbolo ye... (similarité: 0.4317)
--------------------------------------------------------------------------------
Test #6 (bm): ❌
Question: fɔlifɛn jumɛn bɛ kɛ ka tariku sɛbɛn ?
  [+] kora bɛ kɛ ka maanaw sɛbɛn ni dɔnkili ye... (similarité: 0.4971)
  [-] dununba bɛ kɛ ka fɔli dɔn nka a tɛ sɛbɛn... (similarité: 0.3109)
--------------------------------------------------------------------------------
Test #7 (fr→bm): ✅
Question: quel est le rôle principal des griots dans la société malienne traditionnelle ?
  [+] griotw ye daɲɛw laada kɔlɔsibagaw ye... (similarité: 0.8141)
  [-] Ni aw ye a ɲimi ka ɲɛ, o bɛ dumuni toli nɔgɔya... (similarité: -0.1368)
--------------------------------------------------------------------------------
Test #8 (bm→fr): ✅
Question: jeliw nafa ka bon cogo di ?
  [+] les griots sont les gardiens de la tradition orale... (similarité: 0.5094)
  [-] Les forgerons travaillent le métal traditionnel... (similarité: 0.2053)
--------------------------------------------------------------------------------
Test #9 (fr): ❌
Question: citez l'instrument emblématique des conteurs maliens
  [+] la kora sert à accompagner les récits historiques... (similarité: 0.4946)
  [-] le bolon est une harpe arquée pour les cérémonies... (similarité: 0.0668)
--------------------------------------------------------------------------------
Test #10 (bm): ❌
Question: fɔlifɛn jumɛn bɛ kɛ ni juru ye ?
  [+] kora bɛ kɛ ni juru 21 ye... (similarité: 0.6871)
  [-] n'goni bɛ kɛ ni juru 4 ye... (similarité: 0.5840)
--------------------------------------------------------------------------------
Test #11 (fr→bm): ❌
Question: quelle est la fonction sociale des griots ?
  [+] u bɛ tariku laseli ani dɔnkiliw fɛ... (similarité: 0.3256)
  [-] u bɛ farikolo kɛ ni sɛnɛ fɛ... (similarité: -0.1393)
--------------------------------------------------------------------------------
Test #12 (bm→fr): ❌
Question: kuma fɔcogo ɲuman bɛ kɛ sababu ye ?
  [+] une bonne articulation permet une compréhension claire... (similarité: 0.4647)
  [-] parler fort aide à être entendu de loin... (similarité: 0.3137)
--------------------------------------------------------------------------------

📊 Score: 5/12 (41.7%)
Seuil de similarité recommandé : 0.4-0.7 pour les bonnes paires

In [ ]:
from sentence_transformers import SentenceTransformer, util

# 1. Charger le modèle depuis Hugging Face Hub
model = SentenceTransformer("Fatoumataa/embedding_billingue_francais_bambara")

# 2. Paires de test par thème (français-bambara)
test_pairs = [
    # Histoire
    ("Qui a été le premier président du Mali ?", "Mali jamana jamanaden fɔlɔ ye jɔn ye ?"),
    ("En quelle année le Mali a-t-il obtenu son indépendance ?", "Mali jamana y'a fanga sɔrɔ san jumɛn ?"),

    # Culture générale
    ("Quel est l'instrument de musique traditionnel le plus populaire au Mali ?", "Mali jamana kan fɛn jumanba ye jumɛn ?"),
    ("Quelle est la signification du Bogolan ?", "Bogolan ka kuma kɔrɔ ye jumɛn ?"),

    # Géographie
    ("Quel est le plus grand fleuve du Mali ?", "Mali jamana ba jumanba ye jumɛn ?"),
    ("Quelle ville malienne est connue pour ses mosquées en terre ?", "Mali jamana dugu jumɛn ka cɛmancɛ caman sɔrɔ ?"),

    # Mathématiques
    ("Combien font deux plus deux ?", "Saban ni saban ka joli ye jumɛn ?"),
    ("Quelle est la racine carrée de neuf ?", "K'onin tɛmɛnen ka joli ye jumɛn ?")
]

# 3. Paires incorrectes pour comparaison
bad_pairs = [
    ("Qui a été le premier président du Mali ?", "K'onin tɛmɛnen ka joli ye jumɛn ?"),  # Histoire vs Maths
    ("Quel est le plus grand fleuve du Mali ?", "Bogolan ka kuma kɔrɔ ye jumɛn ?")  # Géographie vs Culture
]

# 4. Fonction de test améliorée
def test_similarity(pairs, theme):
    print(f"\n📚 Thème: {theme.upper()}")
    for i, (q1, q2) in enumerate(pairs, 1):
        emb1 = model.encode(q1)
        emb2 = model.encode(q2)
        score = util.cos_sim(emb1, emb2).item()

        print(f"\nPair {i}:")
        print(f"FR: {q1}")
        print(f"BM: {q2}")
        print(f"Similarité: {score:.4f}")
        print("---"*20)

# 5. Exécution des tests
print("🔍 TEST DE SIMILARITÉ BILINGUE FRANÇAIS-BAMBARA 🔍")

# Test par thème
history_pairs = [test_pairs[0], test_pairs[1]]
culture_pairs = [test_pairs[2], test_pairs[3]]
geo_pairs = [test_pairs[4], test_pairs[5]]
math_pairs = [test_pairs[6], test_pairs[7]]

test_similarity(history_pairs, "Histoire")
test_similarity(culture_pairs, "Culture générale")
test_similarity(geo_pairs, "Géographie")
test_similarity(math_pairs, "Mathématiques")

# Test des paires incorrectes
print("\n🚨 TEST DES PAIRES INCORRECTES")
test_similarity(bad_pairs, "Comparaisons incorrectes")

# 6. Test avancé avec recherche sémantique
print("\n🔎 TEST DE RECHERCHE SÉMANTIQUE")
query = "capitale du Mali"
docs = [
    "Bamako ye Mali faaba ye",
    "Mali jamana ka sigida sɔrɔ Bamako",
    "Seku Amadu ye Masina mara ye",
    "Timbuktu ka tɔn don Mali worodugu kan"
]

query_embed = model.encode(query)
doc_embeds = model.encode(docs)

scores = util.cos_sim(query_embed, doc_embeds)[0]

print(f"\nRequête: '{query}'")
for doc, score in zip(docs, scores):
    print(f"📄 {doc} → Score: {score:.4f}")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/29.9k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/697 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

🔍 TEST DE SIMILARITÉ BILINGUE FRANÇAIS-BAMBARA 🔍

📚 Thème: HISTOIRE

Pair 1:
FR: Qui a été le premier président du Mali ?
BM: Mali jamana jamanaden fɔlɔ ye jɔn ye ?
Similarité: 0.2247
------------------------------------------------------------

Pair 2:
FR: En quelle année le Mali a-t-il obtenu son indépendance ?
BM: Mali jamana y'a fanga sɔrɔ san jumɛn ?
Similarité: 0.3505
------------------------------------------------------------

📚 Thème: CULTURE GÉNÉRALE

Pair 1:
FR: Quel est l'instrument de musique traditionnel le plus populaire au Mali ?
BM: Mali jamana kan fɛn jumanba ye jumɛn ?
Similarité: -0.0130
------------------------------------------------------------

Pair 2:
FR: Quelle est la signification du Bogolan ?
BM: Bogolan ka kuma kɔrɔ ye jumɛn ?
Similarité: 0.5919
------------------------------------------------------------

📚 Thème: GÉOGRAPHIE

Pair 1:
FR: Quel est le plus grand fleuve du Mali ?
BM: Mali jamana ba jumanba ye jumɛn ?
Similarité: 0.1779
------------------------------------------------------------

Pair 2:
FR: Quelle ville malienne est connue pour ses mosquées en terre ?
BM: Mali jamana dugu jumɛn ka cɛmancɛ caman sɔrɔ ?
Similarité: 0.1740
------------------------------------------------------------

📚 Thème: MATHÉMATIQUES

Pair 1:
FR: Combien font deux plus deux ?
BM: Saban ni saban ka joli ye jumɛn ?
Similarité: 0.0864
------------------------------------------------------------

Pair 2:
FR: Quelle est la racine carrée de neuf ?
BM: K'onin tɛmɛnen ka joli ye jumɛn ?
Similarité: 0.0359
------------------------------------------------------------

🚨 TEST DES PAIRES INCORRECTES

📚 Thème: COMPARAISONS INCORRECTES

Pair 1:
FR: Qui a été le premier président du Mali ?
BM: K'onin tɛmɛnen ka joli ye jumɛn ?
Similarité: -0.1706
------------------------------------------------------------

Pair 2:
FR: Quel est le plus grand fleuve du Mali ?
BM: Bogolan ka kuma kɔrɔ ye jumɛn ?
Similarité: -0.1959
------------------------------------------------------------

🔎 TEST DE RECHERCHE SÉMANTIQUE

Requête: 'capitale du Mali'
📄 Bamako ye Mali faaba ye → Score: 0.5348
📄 Mali jamana ka sigida sɔrɔ Bamako → Score: 0.5416
📄 Seku Amadu ye Masina mara ye → Score: 0.1660
📄 Timbuktu ka tɔn don Mali worodugu kan → Score: 0.3979

In [ ]:
!pip install -q -U transformers==4.40.0 datasets==2.18.0 accelerate==0.29.0
!pip install -q peft==0.10.0 bitsandbytes==0.43.0 huggingface_hub==0.22.0
!pip install -q wandb==0.16.6 evaluate==0.4.0 sentencepiece einops sacrebleu

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.6/137.6 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.9/73.9 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 58.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 34.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.3/297.3 kB 21.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 62.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 93.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.3/235.3 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.5/213.5 kB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.0/349.0 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 MB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.5/388.5 kB 24.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 30.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.2/208.2 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.7/357.7 kB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 101.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 4.8 MB/s eta 0:00:00